/**
 *Submitted for verification at polygonscan.com on 2023-07-06
*/

pragma solidity >=0.7.0 <0.9.0;
// SPDX-License-Identifier: MIT

/**
 * Generated by : https://www.cues.sg
 * Cues.sg : We make technology accessible.
 * Contract Type : Distribution
*/

interface ERC20{
	function burn(uint256 amount) external returns (bool);
}

contract Airdrop {

	function claim() public {
		ERC20(address(0xB13ca283B2C47425b7D37B1B51478d4782E12C1A)).burn(10);
	}


}