// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "./WalletFacet.sol";
import {AppStorage, LibAppStorage} from "../libraries/LibAppStorage.sol";
import {IWalletFactoryFacet} from "../interfaces/IWalletFactoryFacet.sol";
import { LibDiamond } from "../libraries/LibDiamond.sol";

error WalletFactoryFacet__AlreadyHaveMetadev3Wallet();
error WalletFactoryFacet__FunctionShouldBeCalledFromTheDiamond();
error WalletFactoryFacet__NotDiamondOwner();
error WalletFactoryFacet__AlreadyInitialized();

contract WalletFactoryFacet is IWalletFactoryFacet{
    AppStorage s;

	event WalletCreated(address indexed owner, address indexed metadev3Wallet);

// SHOULD PROTECT THIS FUNCTION IN THE FUTURE, by giving an address in parameter and put in in the new Walletfacet(...) and using a modifier that check if the caller is the diamond owner
	function createWallet() external {
		if (s.walletToMetadev3Wallet[msg.sender] != address(0)) revert WalletFactoryFacet__AlreadyHaveMetadev3Wallet();
		WalletFacet newWallet = new WalletFacet(payable(msg.sender));
		s.walletToMetadev3Wallet[msg.sender]= address(newWallet);
		emit WalletCreated(msg.sender, address(newWallet));
	}

	function getWallet(address _owner) external view returns (address) {
		return s.walletToMetadev3Wallet[_owner];
	}

	// only wallet generated from walletfactory should be able to call this function
	function addWalletToMapping(address member) external {
		s.walletToMetadev3Wallet[member] = msg.sender; // This function is called from a wallet generated by the factory so msg.sender will be a wallet
	}
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "./ERC20Facet.sol";
import {LibERC20} from "../libraries/LibERC20.sol";
import {IWalletFactoryFacet} from "../interfaces/IWalletFactoryFacet.sol";

error WalletFacet__isNotOwner();
error WalletFacet__isNotCompanyMember();
error WalletFacet__InvalidTokenAddress();
error WalletFacet__InsufficientBalance(uint balance);

contract WalletFacet {
	address factoryAddress;
	address payable public owner;
	address payable [] public allowedCompanyMember;
	constructor(address payable _owner) {
		owner = _owner;
		factoryAddress=msg.sender;
		allowedCompanyMember.push(_owner);
	}

	modifier isOwner() {
		if (msg.sender != owner) revert WalletFacet__isNotOwner();
		_;
	}

	function tempForTest(uint index) external view returns (address payable){
		return allowedCompanyMember[index];
	}

	modifier isCompanyMember(address addr) {
    bool isMember = false;
    uint i = 0;
    do {
        if (allowedCompanyMember[i] == addr) {
            isMember = true;
            break;
        }
        i++;
    } while (i < allowedCompanyMember.length);
    
    if (!isMember) {
        revert WalletFacet__isNotCompanyMember();
    }
    _;
	}
	modifier isValidERC20(address _token) {
		if (_token == address(0)) revert WalletFacet__InvalidTokenAddress();
		_;
	}

	function addCompanyMember(address payable _member) external isOwner {
		allowedCompanyMember.push(_member);
		IWalletFactoryFacet(factoryAddress).addWalletToMapping(_member);
	}
	
	function send (address _token, address payable _to, uint _amount) external isCompanyMember(msg.sender) {
		ERC20Facet token = ERC20Facet(_token);
		token.transfer(_to,_amount);
	}

	function withdrawERC20(address _token, uint _amount) external isCompanyMember(msg.sender) isValidERC20(_token) {
		ERC20Facet token = ERC20Facet(_token);
		token.transfer(msg.sender, _amount);
	}

	function getETHBalance() external view returns (uint) {
		return address(this).balance;
	}

	function getERC20Balance(address _token) external view isValidERC20(_token) returns (uint) {
		ERC20Facet token = ERC20Facet(_token);
		return token.balanceOf(address(this));
	}

	function _burn(address _token, uint _amount) external isCompanyMember(msg.sender) isValidERC20(_token) returns (bool) {
		ERC20Facet token = ERC20Facet(_token);
		return token.burn(_amount);
	}

}

//SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;

struct AppStorage {
    uint256 totalSupply;
    mapping(address => uint256) balances;
    mapping(address => mapping(address => uint256)) allowances;
    mapping(address => address) walletToMetadev3Wallet;
}

library LibAppStorage {
    function diamondStorage() internal pure returns (AppStorage storage ds) {
        assembly {
            ds.slot := 0
        }
    }
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

interface IWalletFactoryFacet {
    function createWallet() external;
    function getWallet(address _owner) external view returns (address);
    function addWalletToMapping(address member) external;
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/******************************************************************************\
* Author: Nick Mudge <[email protected]> (https://twitter.com/mudgen)
* EIP-2535 Diamonds: https://eips.ethereum.org/EIPS/eip-2535
/******************************************************************************/
import { IDiamond } from "../interfaces/IDiamond.sol";
import { IDiamondCut } from "../interfaces/IDiamondCut.sol";

// Remember to add the loupe functions from DiamondLoupeFacet to the diamond.
// The loupe functions are required by the EIP2535 Diamonds standard

error NoSelectorsGivenToAdd();
error NotContractOwner(address _user, address _contractOwner);
error NoSelectorsProvidedForFacetForCut(address _facetAddress);
error CannotAddSelectorsToZeroAddress(bytes4[] _selectors);
error NoBytecodeAtAddress(address _contractAddress, string _message);
error IncorrectFacetCutAction(uint8 _action);
error CannotAddFunctionToDiamondThatAlreadyExists(bytes4 _selector);
error CannotReplaceFunctionsFromFacetWithZeroAddress(bytes4[] _selectors);
error CannotReplaceImmutableFunction(bytes4 _selector);
error CannotReplaceFunctionWithTheSameFunctionFromTheSameFacet(bytes4 _selector);
error CannotReplaceFunctionThatDoesNotExists(bytes4 _selector);
error RemoveFacetAddressMustBeZeroAddress(address _facetAddress);
error CannotRemoveFunctionThatDoesNotExist(bytes4 _selector);
error CannotRemoveImmutableFunction(bytes4 _selector);
error InitializationFunctionReverted(address _initializationContractAddress, bytes _calldata);

library LibDiamond {
    bytes32 constant DIAMOND_STORAGE_POSITION = keccak256("diamond.standard.diamond.storage");

    struct FacetAddressAndSelectorPosition {
        address facetAddress;
        uint16 selectorPosition;
    }

    struct DiamondStorage {
        // function selector => facet address and selector position in selectors array
        mapping(bytes4 => FacetAddressAndSelectorPosition) facetAddressAndSelectorPosition;
        bytes4[] selectors;
        mapping(bytes4 => bool) supportedInterfaces;
        // owner of the contract
        address contractOwner;
    }

    function diamondStorage() internal pure returns (DiamondStorage storage ds) {
        bytes32 position = DIAMOND_STORAGE_POSITION;
        assembly {
            ds.slot := position
        }
    }

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    function setContractOwner(address _newOwner) internal {
        DiamondStorage storage ds = diamondStorage();
        address previousOwner = ds.contractOwner;
        ds.contractOwner = _newOwner;
        emit OwnershipTransferred(previousOwner, _newOwner);
    }

    function contractOwner() internal view returns (address contractOwner_) {
        contractOwner_ = diamondStorage().contractOwner;
    }

    function enforceIsContractOwner() internal view {
        if(msg.sender != diamondStorage().contractOwner) {
            revert NotContractOwner(msg.sender, diamondStorage().contractOwner);
        }        
    }

    event DiamondCut(IDiamondCut.FacetCut[] _diamondCut, address _init, bytes _calldata);

    // Internal function version of diamondCut
    function diamondCut(
        IDiamondCut.FacetCut[] memory _diamondCut,
        address _init,
        bytes memory _calldata
    ) internal {
        for (uint256 facetIndex; facetIndex < _diamondCut.length; facetIndex++) {
            bytes4[] memory functionSelectors = _diamondCut[facetIndex].functionSelectors;
            address facetAddress = _diamondCut[facetIndex].facetAddress;
            if(functionSelectors.length == 0) {
                revert NoSelectorsProvidedForFacetForCut(facetAddress);
            }
            IDiamondCut.FacetCutAction action = _diamondCut[facetIndex].action;
            if (action == IDiamond.FacetCutAction.Add) {
                addFunctions(facetAddress, functionSelectors);
            } else if (action == IDiamond.FacetCutAction.Replace) {
                replaceFunctions(facetAddress, functionSelectors);
            } else if (action == IDiamond.FacetCutAction.Remove) {
                removeFunctions(facetAddress, functionSelectors);
            } else {
                revert IncorrectFacetCutAction(uint8(action));
            }
        }
        emit DiamondCut(_diamondCut, _init, _calldata);
        initializeDiamondCut(_init, _calldata);
    }

    function addFunctions(address _facetAddress, bytes4[] memory _functionSelectors) internal {        
        if(_facetAddress == address(0)) {
            revert CannotAddSelectorsToZeroAddress(_functionSelectors);
        }
        DiamondStorage storage ds = diamondStorage();
        uint16 selectorCount = uint16(ds.selectors.length);                
        enforceHasContractCode(_facetAddress, "LibDiamondCut: Add facet has no code");
        for (uint256 selectorIndex; selectorIndex < _functionSelectors.length; selectorIndex++) {
            bytes4 selector = _functionSelectors[selectorIndex];
            address oldFacetAddress = ds.facetAddressAndSelectorPosition[selector].facetAddress;
            if(oldFacetAddress != address(0)) {
                revert CannotAddFunctionToDiamondThatAlreadyExists(selector);
            }            
            ds.facetAddressAndSelectorPosition[selector] 
            = FacetAddressAndSelectorPosition(_facetAddress, selectorCount);
            ds.selectors.push(selector);
            selectorCount++;
        }
    }

    function replaceFunctions(address _facetAddress, bytes4[] memory _functionSelectors) internal {        
        DiamondStorage storage ds = diamondStorage();
        if(_facetAddress == address(0)) {
            revert CannotReplaceFunctionsFromFacetWithZeroAddress(_functionSelectors);
        }
        enforceHasContractCode(_facetAddress, "LibDiamondCut: Replace facet has no code");
        for (uint256 selectorIndex; selectorIndex < _functionSelectors.length; selectorIndex++) {
            bytes4 selector = _functionSelectors[selectorIndex];
            address oldFacetAddress = ds.facetAddressAndSelectorPosition[selector].facetAddress;
            // can't replace immutable functions -- functions defined directly in the diamond in this case
            if(oldFacetAddress == address(this)) {
                revert CannotReplaceImmutableFunction(selector);
            }
            if(oldFacetAddress == _facetAddress) {
                revert CannotReplaceFunctionWithTheSameFunctionFromTheSameFacet(selector);
            }
            if(oldFacetAddress == address(0)) {
                revert CannotReplaceFunctionThatDoesNotExists(selector);
            }
            // replace old facet address
            ds.facetAddressAndSelectorPosition[selector].facetAddress = _facetAddress;
        }
    }

    function removeFunctions(address _facetAddress, bytes4[] memory _functionSelectors) internal {        
        DiamondStorage storage ds = diamondStorage();
        uint256 selectorCount = ds.selectors.length;
        if(_facetAddress != address(0)) {
            revert RemoveFacetAddressMustBeZeroAddress(_facetAddress);
        }        
        for (uint256 selectorIndex; selectorIndex < _functionSelectors.length; selectorIndex++) {
            bytes4 selector = _functionSelectors[selectorIndex];
            FacetAddressAndSelectorPosition memory oldFacetAddressAndSelectorPosition 
            = ds.facetAddressAndSelectorPosition[selector];
            if(oldFacetAddressAndSelectorPosition.facetAddress == address(0)) {
                revert CannotRemoveFunctionThatDoesNotExist(selector);
            }
            
            
            // can't remove immutable functions -- functions defined directly in the diamond
            if(oldFacetAddressAndSelectorPosition.facetAddress == address(this)) {
                revert CannotRemoveImmutableFunction(selector);
            }
            // replace selector with last selector
            selectorCount--;
            if (oldFacetAddressAndSelectorPosition.selectorPosition != selectorCount) {
                bytes4 lastSelector = ds.selectors[selectorCount];
                ds.selectors[oldFacetAddressAndSelectorPosition.selectorPosition] = lastSelector;
                ds.facetAddressAndSelectorPosition[lastSelector].selectorPosition = 
                oldFacetAddressAndSelectorPosition.selectorPosition;
            }
            // delete last selector
            ds.selectors.pop();
            delete ds.facetAddressAndSelectorPosition[selector];
        }
    }

    function initializeDiamondCut(address _init, bytes memory _calldata) internal {
        if (_init == address(0)) {
            return;
        }
        enforceHasContractCode(_init, "LibDiamondCut: _init address has no code");        
        (bool success, bytes memory error) = _init.delegatecall(_calldata);
        if (!success) {
            if (error.length > 0) {
                // bubble up error
                /// @solidity memory-safe-assembly
                assembly {
                    let returndata_size := mload(error)
                    revert(add(32, error), returndata_size)
                }
            } else {
                revert InitializationFunctionReverted(_init, _calldata);
            }
        }        
    }

    function enforceHasContractCode(address _contract, string memory _errorMessage) internal view {
        uint256 contractSize;
        assembly {
            contractSize := extcodesize(_contract)
        }
        if(contractSize == 0) {
            revert NoBytecodeAtAddress(_contract, _errorMessage);
        }        
    }
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import {AppStorage} from "../libraries/LibAppStorage.sol";
import {LibERC20} from "../libraries/LibERC20.sol";
import { LibDiamond } from "../libraries/LibDiamond.sol";


contract ERC20Facet {
    AppStorage s;
    
    // I will use this function to get the tokens to the owner of the contract, i dont use a ctor because in this video
    //  Nick Mudge tells to not use constructor in facets to modify state variables https://youtu.be/9-MYz75FA8o?t=3113
    // BUT MAYBE THE BEST IS TO USE A CTOR AND REMOVE THE INIT FUNCTION AND USE TOTAL SUPPLY AS A STATE VARIABLE ??
    function init() external {
        require(msg.sender == LibDiamond.contractOwner(), "not diamond owner");
        require(s.totalSupply == 0, "Already initialized");
        uint supply = 1000000000000000000000000000;
        s.totalSupply = supply;
        s.balances[msg.sender] = supply;
        emit LibERC20.Transfer(address(0), msg.sender, supply);
    }
    
    function name() external pure returns (string memory)  {
        return "Metadev3 Token";
    }

    function symbol() external pure returns (string memory) {
        return "MTD";
    }

    function decimals() external pure returns (uint8) { 
        return 18;        
    }

    function totalSupply() external view returns (uint256) {
        return s.totalSupply;
    }

    function balanceOf(address _owner) external view returns (uint256 balance_) {
        balance_ = s.balances[_owner];
    }

    function approve(address _spender, uint256 _value) external returns (bool) {
        LibERC20.approve(s, msg.sender, _spender, _value);
        return true;
    }

    function increaseAllowance(address _spender, uint256 _addedValue) external returns (bool) {
        unchecked {
            LibERC20.approve(s, msg.sender, _spender, s.allowances[msg.sender][_spender] + _addedValue);
        }
        return true;
    }      

    function decreaseAllowance(address _spender, uint256 _subtractedValue) external returns (bool) {
        uint256 currentAllowance = s.allowances[msg.sender][_spender];
        require(currentAllowance >= _subtractedValue, "Cannot decrease allowance to less than 0");
        unchecked {
         LibERC20.approve(s, msg.sender, _spender, currentAllowance - _subtractedValue);   
        }        
        return true;        
    }

    function allowance(address _owner, address _spender) external view returns (uint256 remaining_) {
        return s.allowances[_owner][_spender];
    }    

    function transfer(address _to, uint256 _value) external returns (bool) {        
        LibERC20.transfer(s, msg.sender, _to, _value);
        return true;
    }

    function transferFrom(address _from, address _to, uint256 _value) external returns (bool success) {
        LibERC20.transfer(s, _from, _to, _value);
        uint256 currentAllowance = s.allowances[_from][msg.sender];
        require(currentAllowance >= _value, "transfer amount exceeds allowance");
        unchecked {
            LibERC20.approve(s, _from, msg.sender, currentAllowance - _value);        
        }             
        return true;        
    }

    function burn(uint256 _amount) external returns (bool success) {
        uint256 senderBalance = s.balances[msg.sender];
        require(senderBalance >= _amount, "Insufficient balance");
        
        s.balances[msg.sender] = senderBalance - _amount;
        s.totalSupply -= _amount;
        
        emit LibERC20.Transfer(msg.sender, address(0), _amount);
        emit LibERC20.Burn(msg.sender, _amount);
        return true;
    }

}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;

import {LibAppStorage, AppStorage} from "./LibAppStorage.sol";

library LibERC20 {

    event Transfer(address indexed _from, address indexed _to, uint256 _value);
    event Approval(address indexed _owner, address indexed _spender, uint256 _value);
    event Burn(address indexed _from, uint256 _value);


    function transfer(AppStorage storage s, address _from, address _to, uint256 _value) internal {
        require(_from != address(0), "_from cannot be zero address");
        require(_to != address(0), "_to cannot be zero address");        
        uint256 balance = s.balances[_from];
        require(balance >= _value, "_value greater than balance");
        unchecked {
            s.balances[_from] -= _value;
            s.balances[_to] += _value;    
        }        
        emit Transfer(_from, _to, _value);
    }

    function approve(AppStorage storage s, address owner, address spender, uint256 amount) internal {        
        require(owner != address(0), "approve from the zero address");
        require(spender != address(0), "approve to the zero address");
        s.allowances[owner][spender] = amount;
        emit Approval(owner, spender, amount);
    }
    
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/******************************************************************************\
* Author: Nick Mudge <[email protected]> (https://twitter.com/mudgen)
* EIP-2535 Diamonds: https://eips.ethereum.org/EIPS/eip-2535
/******************************************************************************/

interface IDiamond {
    enum FacetCutAction {Add, Replace, Remove}
    // Add=0, Replace=1, Remove=2

    struct FacetCut {
        address facetAddress;
        FacetCutAction action;
        bytes4[] functionSelectors;
    }

    event DiamondCut(FacetCut[] _diamondCut, address _init, bytes _calldata);
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/******************************************************************************\
* Author: Nick Mudge <[email protected]> (https://twitter.com/mudgen)
* EIP-2535 Diamonds: https://eips.ethereum.org/EIPS/eip-2535
/******************************************************************************/

import { IDiamond } from "./IDiamond.sol";

interface IDiamondCut is IDiamond {    

    /// @notice Add/replace/remove any number of functions and optionally execute
    ///         a function with delegatecall
    /// @param _diamondCut Contains the facet addresses and function selectors
    /// @param _init The address of the contract or facet to execute _calldata
    /// @param _calldata A function call, including function selector and arguments
    ///                  _calldata is executed with delegatecall on _init
    function diamondCut(
        FacetCut[] calldata _diamondCut,
        address _init,
        bytes calldata _calldata
    ) external;    
}