/**
 *Submitted for verification at polygonscan.com on 2022-04-11
*/

/* Copyright (c) 2018-2021 SmartContract ChainLink, Ltd.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract VRFRequestIDBase {

  /**
   * @notice returns the seed which is actually input to the VRF coordinator
   *
   * @dev To prevent repetition of VRF output due to repetition of the
   * @dev user-supplied seed, that seed is combined in a hash with the
   * @dev user-specific nonce, and the address of the consuming contract. The
   * @dev risk of repetition is mostly mitigated by inclusion of a blockhash in
   * @dev the final seed, but the nonce does protect against repetition in
   * @dev requests which are included in a single block.
   *
   * @param _userSeed VRF seed input provided by user
   * @param _requester Address of the requesting contract
   * @param _nonce User-specific nonce at the time of the request
   */
  function makeVRFInputSeed(bytes32 _keyHash, uint256 _userSeed,
    address _requester, uint256 _nonce)
    internal pure returns (uint256)
  {
    return  uint256(keccak256(abi.encode(_keyHash, _userSeed, _requester, _nonce)));
  }

  /**
   * @notice Returns the id for this request
   * @param _keyHash The serviceAgreement ID to be used for this request
   * @param _vRFInputSeed The seed to be passed directly to the VRF
   * @return The id for this request
   *
   * @dev Note that _vRFInputSeed is not the seed passed by the consuming
   * @dev contract, but the one generated by makeVRFInputSeed
   */
  function makeRequestId(
    bytes32 _keyHash, uint256 _vRFInputSeed) internal pure returns (bytes32) {
    return keccak256(abi.encodePacked(_keyHash, _vRFInputSeed));
  }
}

// File: @chainlink/contracts/src/v0.6/interfaces/LinkTokenInterface.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

interface LinkTokenInterface {
  function allowance(address owner, address spender) external view returns (uint256 remaining);
  function approve(address spender, uint256 value) external returns (bool success);
  function balanceOf(address owner) external view returns (uint256 balance);
  function decimals() external view returns (uint8 decimalPlaces);
  function decreaseApproval(address spender, uint256 addedValue) external returns (bool success);
  function increaseApproval(address spender, uint256 subtractedValue) external;
  function name() external view returns (string memory tokenName);
  function symbol() external view returns (string memory tokenSymbol);
  function totalSupply() external view returns (uint256 totalTokensIssued);
  function transfer(address to, uint256 value) external returns (bool success);
  function transferAndCall(address to, uint256 value, bytes calldata data) external returns (bool success);
  function transferFrom(address from, address to, uint256 value) external returns (bool success);
}

// File: @chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

/**
 * @dev Wrappers over Solidity's arithmetic operations with added overflow
 * checks.
 *
 * Arithmetic operations in Solidity wrap on overflow. This can easily result
 * in bugs, because programmers usually assume that an overflow raises an
 * error, which is the standard behavior in high level programming languages.
 * `SafeMath` restores this intuition by reverting the transaction when an
 * operation overflows.
 *
 * Using this library instead of the unchecked operations eliminates an entire
 * class of bugs, so it's recommended to use it always.
 */
library SafeMathChainlink {
  /**
    * @dev Returns the addition of two unsigned integers, reverting on
    * overflow.
    *
    * Counterpart to Solidity's `+` operator.
    *
    * Requirements:
    * - Addition cannot overflow.
    */
  function add(uint256 a, uint256 b) internal pure returns (uint256) {
    uint256 c = a + b;
    require(c >= a, "SafeMath: addition overflow");

    return c;
  }

  /**
    * @dev Returns the subtraction of two unsigned integers, reverting on
    * overflow (when the result is negative).
    *
    * Counterpart to Solidity's `-` operator.
    *
    * Requirements:
    * - Subtraction cannot overflow.
    */
  function sub(uint256 a, uint256 b) internal pure returns (uint256) {
    require(b <= a, "SafeMath: subtraction overflow");
    uint256 c = a - b;

    return c;
  }

  /**
    * @dev Returns the multiplication of two unsigned integers, reverting on
    * overflow.
    *
    * Counterpart to Solidity's `*` operator.
    *
    * Requirements:
    * - Multiplication cannot overflow.
    */
  function mul(uint256 a, uint256 b) internal pure returns (uint256) {
    // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
    // benefit is lost if 'b' is also tested.
    // See: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522
    if (a == 0) {
      return 0;
    }

    uint256 c = a * b;
    require(c / a == b, "SafeMath: multiplication overflow");

    return c;
  }

  /**
    * @dev Returns the integer division of two unsigned integers. Reverts on
    * division by zero. The result is rounded towards zero.
    *
    * Counterpart to Solidity's `/` operator. Note: this function uses a
    * `revert` opcode (which leaves remaining gas untouched) while Solidity
    * uses an invalid opcode to revert (consuming all remaining gas).
    *
    * Requirements:
    * - The divisor cannot be zero.
    */
  function div(uint256 a, uint256 b) internal pure returns (uint256) {
    // Solidity only automatically asserts when dividing by 0
    require(b > 0, "SafeMath: division by zero");
    uint256 c = a / b;
    // assert(a == b * c + a % b); // There is no case in which this doesn't hold

    return c;
  }

  /**
    * @dev Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
    * Reverts when dividing by zero.
    *
    * Counterpart to Solidity's `%` operator. This function uses a `revert`
    * opcode (which leaves remaining gas untouched) while Solidity uses an
    * invalid opcode to revert (consuming all remaining gas).
    *
    * Requirements:
    * - The divisor cannot be zero.
    */
  function mod(uint256 a, uint256 b) internal pure returns (uint256) {
    require(b != 0, "SafeMath: modulo by zero");
    return a % b;
  }
}

// File: @chainlink/contracts/src/v0.6/VRFConsumerBase.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

/** ****************************************************************************
 * @notice Interface for contracts using VRF randomness
 * *****************************************************************************
 * @dev PURPOSE
 *
 * @dev Reggie the Random Oracle (not his real job) wants to provide randomness
 * @dev to Vera the verifier in such a way that Vera can be sure he's not
 * @dev making his output up to suit himself. Reggie provides Vera a public key
 * @dev to which he knows the secret key. Each time Vera provides a seed to
 * @dev Reggie, he gives back a value which is computed completely
 * @dev deterministically from the seed and the secret key.
 *
 * @dev Reggie provides a proof by which Vera can verify that the output was
 * @dev correctly computed once Reggie tells it to her, but without that proof,
 * @dev the output is indistinguishable to her from a uniform random sample
 * @dev from the output space.
 *
 * @dev The purpose of this contract is to make it easy for unrelated contracts
 * @dev to talk to Vera the verifier about the work Reggie is doing, to provide
 * @dev simple access to a verifiable source of randomness.
 * *****************************************************************************
 * @dev USAGE
 *
 * @dev Calling contracts must inherit from VRFConsumerBase, and can
 * @dev initialize VRFConsumerBase's attributes in their constructor as
 * @dev shown:
 *
 * @dev   contract VRFConsumer {
 * @dev     constuctor(<other arguments>, address _vrfCoordinator, address _link)
 * @dev       VRFConsumerBase(_vrfCoordinator, _link) public {
 * @dev         <initialization with other arguments goes here>
 * @dev       }
 * @dev   }
 *
 * @dev The oracle will have given you an ID for the VRF keypair they have
 * @dev committed to (let's call it keyHash), and have told you the minimum LINK
 * @dev price for VRF service. Make sure your contract has sufficient LINK, and
 * @dev call requestRandomness(keyHash, fee, seed), where seed is the input you
 * @dev want to generate randomness from.
 *
 * @dev Once the VRFCoordinator has received and validated the oracle's response
 * @dev to your request, it will call your contract's fulfillRandomness method.
 *
 * @dev The randomness argument to fulfillRandomness is the actual random value
 * @dev generated from your seed.
 *
 * @dev The requestId argument is generated from the keyHash and the seed by
 * @dev makeRequestId(keyHash, seed). If your contract could have concurrent
 * @dev requests open, you can use the requestId to track which seed is
 * @dev associated with which randomness. See VRFRequestIDBase.sol for more
 * @dev details. (See "SECURITY CONSIDERATIONS" for principles to keep in mind,
 * @dev if your contract could have multiple requests in flight simultaneously.)
 *
 * @dev Colliding `requestId`s are cryptographically impossible as long as seeds
 * @dev differ. (Which is critical to making unpredictable randomness! See the
 * @dev next section.)
 *
 * *****************************************************************************
 * @dev SECURITY CONSIDERATIONS
 *
 * @dev A method with the ability to call your fulfillRandomness method directly
 * @dev could spoof a VRF response with any random value, so it's critical that
 * @dev it cannot be directly called by anything other than this base contract
 * @dev (specifically, by the VRFConsumerBase.rawFulfillRandomness method).
 *
 * @dev For your users to trust that your contract's random behavior is free
 * @dev from malicious interference, it's best if you can write it so that all
 * @dev behaviors implied by a VRF response are executed *during* your
 * @dev fulfillRandomness method. If your contract must store the response (or
 * @dev anything derived from it) and use it later, you must ensure that any
 * @dev user-significant behavior which depends on that stored value cannot be
 * @dev manipulated by a subsequent VRF request.
 *
 * @dev Similarly, both miners and the VRF oracle itself have some influence
 * @dev over the order in which VRF responses appear on the blockchain, so if
 * @dev your contract could have multiple VRF requests in flight simultaneously,
 * @dev you must ensure that the order in which the VRF responses arrive cannot
 * @dev be used to manipulate your contract's user-significant behavior.
 *
 * @dev Since the ultimate input to the VRF is mixed with the block hash of the
 * @dev block in which the request is made, user-provided seeds have no impact
 * @dev on its economic security properties. They are only included for API
 * @dev compatability with previous versions of this contract.
 *
 * @dev Since the block hash of the block which contains the requestRandomness
 * @dev call is mixed into the input to the VRF *last*, a sufficiently powerful
 * @dev miner could, in principle, fork the blockchain to evict the block
 * @dev containing the request, forcing the request to be included in a
 * @dev different block with a different hash, and therefore a different input
 * @dev to the VRF. However, such an attack would incur a substantial economic
 * @dev cost. This cost scales with the number of blocks the VRF oracle waits
 * @dev until it calls responds to a request.
 */
abstract contract VRFConsumerBase is VRFRequestIDBase {

  using SafeMathChainlink for uint256;

  /**
   * @notice fulfillRandomness handles the VRF response. Your contract must
   * @notice implement it. See "SECURITY CONSIDERATIONS" above for important
   * @notice principles to keep in mind when implementing your fulfillRandomness
   * @notice method.
   *
   * @dev VRFConsumerBase expects its subcontracts to have a method with this
   * @dev signature, and will call it once it has verified the proof
   * @dev associated with the randomness. (It is triggered via a call to
   * @dev rawFulfillRandomness, below.)
   *
   * @param requestId The Id initially returned by requestRandomness
   * @param randomness the VRF output
   */
  function fulfillRandomness(bytes32 requestId, uint256 randomness)
    internal virtual;

  /**
   * @dev In order to keep backwards compatibility we have kept the user
   * seed field around. We remove the use of it because given that the blockhash
   * enters later, it overrides whatever randomness the used seed provides.
   * Given that it adds no security, and can easily lead to misunderstandings,
   * we have removed it from usage and can now provide a simpler API.
   */
  uint256 constant private USER_SEED_PLACEHOLDER = 0;

  /**
   * @notice requestRandomness initiates a request for VRF output given _seed
   *
   * @dev The fulfillRandomness method receives the output, once it's provided
   * @dev by the Oracle, and verified by the vrfCoordinator.
   *
   * @dev The _keyHash must already be registered with the VRFCoordinator, and
   * @dev the _fee must exceed the fee specified during registration of the
   * @dev _keyHash.
   *
   * @dev The _seed parameter is vestigial, and is kept only for API
   * @dev compatibility with older versions. It can't *hurt* to mix in some of
   * @dev your own randomness, here, but it's not necessary because the VRF
   * @dev oracle will mix the hash of the block containing your request into the
   * @dev VRF seed it ultimately uses.
   *
   * @param _keyHash ID of public key against which randomness is generated
   * @param _fee The amount of LINK to send with the request
   *
   * @return requestId unique ID for this request
   *
   * @dev The returned requestId can be used to distinguish responses to
   * @dev concurrent requests. It is passed as the first argument to
   * @dev fulfillRandomness.
   */
  function requestRandomness(bytes32 _keyHash, uint256 _fee)
    internal returns (bytes32 requestId)
  {
    LINK.transferAndCall(vrfCoordinator, _fee, abi.encode(_keyHash, USER_SEED_PLACEHOLDER));
    // This is the seed passed to VRFCoordinator. The oracle will mix this with
    // the hash of the block containing this request to obtain the seed/input
    // which is finally passed to the VRF cryptographic machinery.
    uint256 vRFSeed  = makeVRFInputSeed(_keyHash, USER_SEED_PLACEHOLDER, address(this), nonces[_keyHash]);
    // nonces[_keyHash] must stay in sync with
    // VRFCoordinator.nonces[_keyHash][this], which was incremented by the above
    // successful LINK.transferAndCall (in VRFCoordinator.randomnessRequest).
    // This provides protection against the user repeating their input seed,
    // which would result in a predictable/duplicate output, if multiple such
    // requests appeared in the same block.
    nonces[_keyHash] = nonces[_keyHash].add(1);
    return makeRequestId(_keyHash, vRFSeed);
  }

  LinkTokenInterface immutable internal LINK;
  address immutable private vrfCoordinator;

  // Nonces for each VRF key from which randomness has been requested.
  //
  // Must stay in sync with VRFCoordinator[_keyHash][this]
  mapping(bytes32 /* keyHash */ => uint256 /* nonce */) private nonces;

  /**
   * @param _vrfCoordinator address of VRFCoordinator contract
   * @param _link address of LINK token contract
   *
   * @dev https://docs.chain.link/docs/link-token-contracts
   */
  constructor(address _vrfCoordinator, address _link) public {
    vrfCoordinator = _vrfCoordinator;
    LINK = LinkTokenInterface(_link);
  }

  // rawFulfillRandomness is called by VRFCoordinator when it receives a valid VRF
  // proof. rawFulfillRandomness then calls fulfillRandomness, after validating
  // the origin of the call
  function rawFulfillRandomness(bytes32 requestId, uint256 randomness) external {
    require(msg.sender == vrfCoordinator, "Only VRFCoordinator can fulfill");
    fulfillRandomness(requestId, randomness);
  }
}

pragma solidity 0.6.6;

contract fetchVRFNumberForCallawayDrawing is VRFConsumerBase {
    //Polygon Mainnet
    address internal contractOwner;
    address internal vrfCoordinator = 0x3d2341ADb2D31f1c5530cDC622016af293177AE0;
    address internal linkToken = 0xb0897686c545045aFc77CF20eC7A532E3120E0F1;
    bool internal permanentlyStop = false;
    bool internal coordinatorBlocked = false;
    bytes32 internal keyHash = 0xf86195cf7690c55907b2b611ebb7343a6f649bff128701cc542f0569e2c549da;
    uint256 internal fee =  0.0001 * 10 ** 18;
    bytes32 public requestIDGenerated;
    uint256 public randomNumberGenerated;
    address[]public addresses=[0x004BC2dC0cF053CC3e767541e559a12d911e04aa, 0x00578f555EbF2308318438a1a679F761b788f2a1, 0x03C4dcDbD7Efc4fD32e2C0E92D4E1F8B778e1A56, 0x03DaD5aeF5e695953A5308F5DfA598BF69ca6b12, 0x046659bB263FD831e3e1383E7AcB6c37B622b29f, 0x05E2461c8c10138aEE241268f28dE6003D3DBAdB, 0x06a521Cb6982EE8E763276fA0C90B3eC8b0414CC, 0x0737880a1866Bfbda9dea62c91BA00df6C79f395, 0x078ad2Aa3B4527e4996D087906B2a3DA51BbA122, 0x0873a7c910bf5D6437050350A1460A051c2600De, 0x08b5D278a116665AeECF16E60f87891aBbbe492A, 0x09759c0Ccc5e9518C33B237B97177d8Bd86DD931, 0x0be4185F441599Aa2300fAabDDd35FE1245e14F5, 0x0c18cc3A37E6969Df5CCe67D1579d645115b4861, 0x0C7c3FE3aC6ea456F3CbCA4A4DD649F8B17BA632, 0x0D4fF60D09B8Fd790a7663dA86a791C2FeD41a23, 0x0e917dCFfB792dbfb36B75AfcC1a5D6174EC94e2, 0x0f642fD5641bb86228137E0F67eAE10338aD26D9, 0x10480a09c087DEB80A1273566642C11DDD9dCEf8, 0x120cE68a93862375A5ae8b7014fD5e28a166167e, 0x12a0E25E62C1dBD32E505446062B26AECB65F028, 0x12cc03a14B954ef87CAF59D2adfe234378a9774B, 0x14202C79dc15CeBBa5115AdCe8a457F49BC71120, 0x14441AC732C0d8cf15f10043D355dA11c831d828, 0x151771a16117293000120fCCdEb96CFd419F3663, 0x160e5B66f58924736B0a264f25ffd01e6732C39f, 0x16564e4f9B09B672e58554559e1ff1031D123a54, 0x166aF43E109930652c59C214FCA62090668C28Db, 0x16C6aFC1e91c685FeF2bbBeA4Ced762ea8660Ae3, 0x176CDD450bcC8F4F9b83f1435D39770bf757Bf72, 0x188C30E9A6527F5F0c3f7fe59B72ac7253C62F28, 0x18E750D0F3776fe4d023A44dBDc365DB98C54bc5, 0x198205DaFc9c35C6772DBf4C68a6F0CEB15007cB, 0x19b96CBD5cAAA33a9B30DBCb849Bee4296b0A4a6, 0x1A6B6a319d119AAdF86Ed5FF3b578D4f7cf746ac, 0x1B2965dC3B1697DD10b7126EC7393d79cdA2cF91, 0x1Bc2C46d6A3c1A1DEE9B623FCA10d72987DC639f, 0x1c090910af3D76Bf136C5309B74021e8F8C8B5f6, 0x1D1F86dDd0F729154C6C87588f3c8ad740eE3385, 0x1DFFDb114e58baEdBD25290A1EffFa9fC3726D1f, 0x20535428e340dCB0138028fD641Fbb161b6986F7, 0x22322380bA90C486320CeC43620d9Dc540004586, 0x225189A1EA477a62FE4d27CF30aCa8B9168441D0, 0x23324ed44904260fE555B18E5Ba95C6030B9227d, 0x24435205EaF97DF22b6F2A2463bA039497596Ba4, 0x26011974D9919BA43c83B5C89a5D8f99ee7387f2, 0x27154a73C0b95B742fD5D87102c8a175B886Ac38, 0x27b5593b682C0935f1FADA134F83c760f46a0562, 0x280A156f28488D38897074110588e3B5493Dfe79, 0x288DeF8225b9E150dc8789e5291CfC5c7E35Eb35, 0x294437c00EF6C50b2e0956246F8976D22E6847a1, 0x2B6247079ddD8e81B34093e911284253bd455EF6, 0x2b998e3F4b17dc444F5bB9f3b657683749D805e9, 0x2Cc76Af6104A69975e16C4110fE283a09d150BA5, 0x2Cfd25f7C59c5F99bFe2c85399103600a6A6f548, 0x2d01841A5C9205107275e68a20F43D598a4bf5Fb, 0x2d44c0388316d951922ca5Ad5699167AD5104700, 0x2D70f22EFf470F09259093434d617428a69317D7, 0x2D9ec72A35afcd8cE9CBC9Bb481a1790b71aa5Da, 0x2Dceb470f56007c73dB10C1438640C8e79d1E913, 0x2E0D63fFCB08eA20fF3AcDbB72dfEc97343885d2, 0x308462DdeDE7627dc88bC55a8cD0DC09E9590422, 0x3125840Ed73f65F4091E3Ad269AaA27f0Bc793C0, 0x320E106911109efa4223b99FD1A5F7aaAD863717, 0x3222E57551E30D7610dC9f945f41a0Ac8615Ec71, 0x329321a7AC6F81d3b5750c1d298F7484D18896e6, 0x32D96a92337d46FC2A2cc2294Bf5d952CFb2a007, 0x33Ec0e01E2dd454D658E3ae748779F390024A5Cd, 0x34cC1c863f1d131637BEa58472580cf8480d3F37, 0x352C1eCaE7a791Da5d7B1857033e4E620A8a8928, 0x3546BD99767246C358ff1497f1580C8365b25AC8, 0x35632b6976b5b6eC3F8D700FAbB7e1e0499C1BfA, 0x36a0C7B860A4715939EF5B2D1A47aEdc6c89423A, 0x36Cd58CBc7e7918CDc93dA345504162130043ba9, 0x378F1B3C40D270FDe4ac3C7A1fe3407b15Ed1aA0, 0x3B8D4451AC06EAD65f387197A25b1d9D4e4d0fBb, 0x3DC6158e2832B46bb3486305dd754D1559b545b5, 0x3df65EAF60F2470e4A581f1b065769eFF1cB8baE, 0x3E0f589d68f839c5b9e92598370E4728A193eDfB, 0x3Ec6f76f0d4c8fA3688222e937279E504a42978a, 0x4280172C9dDa7f6b9E820FE4ad3FB3723d4604Dd, 0x453a6B83ba2Dd467004f96b3Ae5dd769F3dA0995, 0x46495fEB2c9781b7b67c9a1d483e37F1033f9990, 0x4803351533528aB489812ab67366D339ab8ed61d, 0x4AafFb477792b9a47fa94c636c369EBfc1aab1f0, 0x4Aca3ccAaE44172DfFA7C45cc3F489eB05363333, 0x4B4DF3B4c0A893C7BeefE72e1b8DAe7654ae6f47, 0x4caDFE63af96404BcB3FbEF877Dc7AAf2593156d, 0x5000e435C595b63c097FC3813900147e4c72B87E, 0x5069caC1fF947A07b2c19EfA0FD6d42403cbcAB2, 0x5208D1C67B97f12b5E99b56218e70F5D2f5a871A, 0x539f209d9ff36F5CEf47A9cEd931EAF211CB5ad4, 0x5460675E258B0350170C6b6069800730239c3Cde, 0x5491cf37Ecb4aa558Cf19131DC7B8712020cC666, 0x55d5C69A8573f046E074cC203Ead44c6F49fd61e, 0x57776F822aA296aA58c93B89e16b1243a9dbB096, 0x57b0e9c1eafD1d144C186a2Dae435A5e8bEA2eb9, 0x5954A0627b5813E6Cb31087fa16728D81977e072, 0x59aEe0e033D64c68Fb2A1323F4825799141938F4, 0x5c4eab549a528Bf15c47A01e174500010997235c, 0x5d54DBAc524Eed9FE4606F65fC0f069E704323a6, 0x5e130cB7F8CDCfB5A15018ee5846769703Ec4478, 0x5E46D8Ade00a753D2901eb3d9B252e0e611E10d5, 0x5F3Cb118b93237b2b0EC7205EC43807e5D4D63e6, 0x5f6DD98a74761939A55383EBf679e0617F7878fA, 0x6280aEB92C12ef44e04a053d3d23E563b4217382, 0x6282e24BAAAF04c984e8AE7CD0C763709743Cf9d, 0x6419606547BAa74d7E69f1EA272259535e2522A1, 0x64823B19255825A0db8a9FC34B032adE9fba7B83, 0x64f82728A11e0FA5e27E15FB1937822Ba3169Ab6, 0x65F2Edecfbf9a675e7353eF105973e2ea515fe79, 0x66d12490943f18103E4634A6F8F7275Ce33B6876, 0x66dF013Fd8AcC69c12A3477B5FaaE009ef4E6d73, 0x670E1b5DC2dB6af9094dDEfB4D356BA2E60Aba8d, 0x6741061a2c3d23A76C56D427dAC2327A3d21eA69, 0x679fae84F998Ff736D2e50C0288E82Cb6df2cD4F, 0x67DaE9571396b01743C6C93E9f62527134117355, 0x6808C8F473363D085D8D8Ece4b53966cAD81Ee4A, 0x681Cbae1C41e5eeC8411dD8e009fA71F81D03F7F, 0x6880968c5C21039B89f72f6DAdbE54462848E3f4, 0x68f37f79b10bfD61f925b68d18F76a06032F8fb5, 0x691E6307E21298708aCA365f2b3A11C48D6d6be3, 0x698fa6437475F3F86Df33eA0cb612AD529954811, 0x69C05144e5840cB57d420792Fce17a73Ce206B1E, 0x69eF61AFc3AA356e1ac97347119d75cBdAbEF534, 0x6A316f344bDa31e6687173c97c839C7160dD2Cd1, 0x6A52cE694a27f98F515edF3841f2432D74a1DE5B, 0x6A7875491F1A539b488Bdde2a5d3660879f215c3, 0x6acEA56Bb5E8b7a8A403872c1CD655E6fBACD218, 0x6B6fC01183ca5AbDb963B7f35Ee3838E4A1A213b, 0x6dd9c7deF4B5355121F479b6dcf1f68cEE608404, 0x6eBD7c0d6D7B6bEa3F2Fd7767DC0e9992dc37Fe6, 0x721961EE8704208D21D071AA41F65D8eD479B3F1, 0x72647A46eB46C3A5c7CE1026798425870b8072E9, 0x73Be883866b3D82e5dfD696ac60Aae3390C61044, 0x74e4e135108FCeD820436f177Ef4e7e7B55639ef, 0x750650d39D41cbF2afD591C22A204634EAa60db5, 0x758ae9264A53F5d634960C0d2D330070528E97D2, 0x75d65178fF8D58C8CD56A2aFfBa0E49869d1abE0, 0x7689E30437477714E901E55CAd0bBf82BA3FFD5E, 0x769eBE155dFa8b7f5EC6b1b138F4d7e741774E64, 0x779453c007e9eD30Fdb1c320ba1E48f373Fe5338, 0x78C89F607113fD12943b0a0D4f3AD15F19350557, 0x79206B9EE1b48Ad2eE925aC0f119A4DE93509F97, 0x797435fA15e74c76c8036028812d5b1a761a851b, 0x7A69a8399740fcB54a182957181a5FCA675e1eF5, 0x7a7424a37aC9bc8140266f1514c2FDd68Da080AA, 0x7c27479b93e386d33beFEBa40064F16CC9d1e110, 0x7Cf67A1A486D5716517A989F180112ba26D1Afcf, 0x7F495c24A4D893416011DB39452c5013d0DF90A9, 0x80b2B6ACBB2744859C04c7DA78373Dc62f523398, 0x813ADe2e74Ca09ea3d1e4797343f7570AfaF6565, 0x8180Cf3d0cC34d5a8a8A4721a8a276f890Ce6fF9, 0x8297A5971a05903D4d33453425D1B800730B10e7, 0x82C08D8C52C65863b1f75B9d2b79714ddaCD77F2, 0x84A11655a2A9024Ac2a78793f350AE7BaF9fB3B3, 0x85A1f25EA31e9850B63943F2E21F306d0536f018, 0x85b608cB4AE6b8E7A5d493CD13F1DEe8e8efa701, 0x876Ea6Ea0f4F5872C729Cf86b7EffaDd79147616, 0x898F43EEC290c12B09a8e06B2D60E2726E86153b, 0x89b68CBA02637CfB1266f0DeCe2856B040b563C3, 0x8a2e722c2f167283E38FFee0Ee5F1a035596915f, 0x8B77F3D65A53eF7F5cef97A1EFe424B1367EBec3, 0x8b9aeB3aaC88F59d7441216dD37BcB98bf8a6B79, 0x8D12B8c3bEf358d1901d891a74FA801aBa2b79B0, 0x8d4f291680e60C63C057d3Af2980EC7895985c52, 0x8e2dDC9502c2C25e2C53ddaCd3B1f86bcB1Ecb39, 0x90D530669A307e21f12de0151DC5Aa3c6f435830, 0x9260ae742F44b7a2e9472f5C299aa0432B3502FA, 0x92dDd38f42a405FAcbF3EC106adD10Ce8BbE8e16, 0x92F1Ff14A80ea8c23028A40c74c05bB994EA0EE2, 0x9324d936B9A0D3a4518ffA762fA9186d88073be9, 0x93859f9eD99E9f6d273404a20171eA5D6A378C57, 0x938F3aA7d81e3aD48b0525c02F0AcE0E79Bb9D52, 0x9428E55418755b2F902D3B1f898A871AB5634182, 0x947c3A2Ae60FDF9cC6c5052A69b1da910939a78E, 0x94fe7f64F8aEdf03da9fc47362A9DA854db5F399, 0x956cD43b221C3CeDaD1542359c7aCE7704aFF956, 0x95FDb5DEDfC613Ba227E9F0c0168Dc80917dAE2e, 0x961FDcC7b95476E97918D56507F70f0cb065FcFC, 0x962F171449D3dD573fFFf59d34cC80e9F87c0E76, 0x9686962604B22EFF0fB99EF0959Ae01897546DcF, 0x97b85Ff1B0E038715570a377e35c08EFA74C2CC6, 0x994da0c3437a823F9e47dE448B62397D1bDfDdBa, 0x99eD4F38f5a4e731dbF8fc079D4dE7c9fa5C91fB, 0x9a116b9B8531d83c2e1Ac61BAbd4Fdf622b2dbb9, 0x9a11E786b40d16F5DE7c7DDdE39E09321d923F27, 0x9A39f286E1CD710Da14E45Ac124e38F2b6242622, 0x9B921faD875b06183d3992A125026c89915D71F6, 0x9e1088BEaeeFB9279427267402E24581B459cfa8, 0x9e9ad816a2Eb29a9Df82D0d946998049a45C5b0E, 0x9ed3dB7a8ec964Ef0813eDb7bf3FF514a25fAE70, 0x9f0574a5F28779A1A682cFE4bbD090ee058d07AA, 0x9f49a41972bbC83BFE80d9685876eF44051e6dD1, 0x9FEF296D8dc2E5c3ceAe453b88ea69632D7B4A5e, 0xA0a896a43A388cDffC0FE751776eF0cc1CF59432, 0xA0ab8Eddf14a5174688E2eb1bdb69CDF377142C3, 0xA0f3907d14B59BB737aA02291CD3E5774d87f31e, 0xA2741aD3dB75576f2974a8A15EA9E910ab006356, 0xA2dC61ccf1C0B8dd305b82DA1F43FE8289118fa7, 0xa3E717740f6C0A595f445EbA9fbc5a4c7abD0BBA, 0xA4ca1b15fE81F57cb2d3f686c7B13309906cd37B, 0xA4D525E5A1dD7F93ab1dD8f71CE6B024e25f7Db8, 0xa513A771F26fd9EC657852a9C4F42A00D3436954, 0xa59Fe57dDcb393Dd3Dcaa2bA2766e10D4F38e339, 0xa6d83E92c3f301885df47F269F212279bC08d0b4, 0xA86b58aa0FC5EAcC647C1Ffe124D4cF3ffaa5978, 0xA9FFa0876e2ca0878307A87d771062C5D8D7D7FC, 0xaAFB72268bC941abE4c975De2571c289046A6b26, 0xAB3EBd5025fF4bd0d48B0049383a0496Cd62F90F, 0xac026bf15e12A8B6879dB279c2EF7c7699111548, 0xAe381AD5b12Cf88F447Ec0E1eC852D60A7E13A87, 0xAf3E252f3190EC77A3a1e07A21c6369A396134eE, 0xAFb5eE18894945A36EF7d20512b2a36b76bd909D, 0xb102188FF7c95aC977DEF3cEb758165af81Aed81, 0xb1c0813D37214886B63bB52b3e5e9c53A372F2C6, 0xB273b47a788aa305C5C65Fa6B56159A4d306d788, 0xB2a8671BFb526B4fBB0831cbe7a0424440098F03, 0xB2FeB9390133877038a5044b15156e3e636D624C, 0xB349150d6270152ca24064ec78ce8C7d7Af9f203, 0xb52E2dbf7f59adA1F56360Ab662041748650Ae06, 0xB810D1238dC5E5D664eBC5d19B0Fd2C28d42968D, 0xB81E82cF70d5F5770734857529ED0fcD32EBD3fD, 0xb8ab59B528d4B6a49CcA41d528C34472DAbe350E, 0xB9f8841AFFA12E59C1A9207d5B4a215F05163E98, 0xbaA56a60CfFf61e740B7594b3368350e2b6975F9, 0xbBCD5C295F5Fb307B7114bf0B974b5b355415e0D, 0xbc074b6707053A349D44656B2a2156244182CAcb, 0xbC07B76e4C63E7B91c6E0395312D88D20449b106, 0xbCb2A76B539974aE57f61B570A0297C748B0062d, 0xbd8a92E249090249c5fB2FF71e47B69fb650d3AF, 0xBDb6fdd2bF2Aa01051540a0630ae568282a4bBef, 0xbdC6f12F436e505AC0f3EAbfb005a6fA25bff4bC, 0xbdf67d7D56744Da479Db200D8E0Eb195587d72eE, 0xBF7f645aEa979EB5894Be7969D9021bFB559a223, 0xbF91459018A2526C745979466b09DBD1D239A41d, 0xc026Fcdc9607234fEE5DA88B585ed2c9b0733942, 0xC0536c11D4B897c8Eac1BC1C6FeA0a2506BF1026, 0xc19A3f5d8bB5f10718527e2296aEb2F5C8Dc2974, 0xc2b3C6589453D4b900319eB956CaC6aF4cC41908, 0xc3670173910801A082F2650Fd9d2d0B587248d44, 0xc375462ddC25926b943000e51133F8F229f757Bc, 0xC454E2B4EbB3C74B2Caf83e74067A8055B375e4E, 0xc4960CC8d469EF0b72caB8E1c57b5957B8b48c65, 0xc563cC8B7a34Ca97E1159132549a000481122a1E, 0xc5Da6fA89CfBECb0310b413E05dC98CA2F875864, 0xc643C9411a6B489e9833b16631140F42bBfCb6d1, 0xC75291B6e917a1fc72ec396883eA005498dC0e55, 0xc77a1222f675b4142dEd8998E7CB938Fea1dB44D, 0xc781196AbE064A21171045732e674121533d338C, 0xC7dED8D808fc92E2f1696BF8B130e3f9984c7529, 0xC9B93b198d4B97ba9829a52f85eBA561f387AEb2, 0xCa11d10CEb098f597a0CAb28117fC3465991a63c, 0xCA50Cc37abaA58d19E3A23CCB086f17F8384cb3C, 0xcc139276fF0BE2dd9485d24C8E33e1C0b9D2E2DF, 0xccCCa855866CBffd38C4b9E151441bfF414176f0, 0xcd492831d1f8A27C2E7d54E340eE1337b1BdF4a3, 0xD239fEbd25f7318ea099E1b4Eb2c2AC9e1a0F787, 0xD26AFEa5C8fDf21c43ffE290BcCC6A46D978EF2f, 0xd2AAe3054D5CbD8Ec640d545d30Bd273A57e413a, 0xD33E6E0E14F5A94F07bdAE82d4F27bd1e1293125, 0xd419d53817E1DAA7B2f72E51707774f3ff0A54A3, 0xD4b6eA173999FE4ebA469a39a6526133d6B5109d, 0xd59C18b27103322662e2b5A3E8f48DD77B60b661, 0xD6EC0742A70A2592aeBA61e3B7bEB9f2E6aa1BC1, 0xD7076AcC76d4379610fbA0dDDB1d35aA1280fc89, 0xd8936E602E38dfEe5d6466865068b94b1943DEBF, 0xD97cf2c5B10B297f03F57DA741BC341d200e1911, 0xDB852c103F1E1FC00FBb5CdB2550FB4ce1F459D6, 0xdC7F3c5Fc1Ce22E8D8F2C35029055BCC06eA1Dfc, 0xDc9dcE81CB89db0C27C477204f272bBF3bBb2326, 0xDDc70166156eC1f116679De84C50F88840Cf3dCB, 0xddc93DBB6889e85ee9a16a7DFeF8F20FA7453f61, 0xde45Ac1DdB50D0c7DDb7ce66b3AF6A696AEc6035, 0xdEdD75cAAB1Fc3241F9e81A08E0988D333A4d4fF, 0xDeEe167CDa039bf00f9395Ede20C945cdC83a7ba, 0xdF157B7Bc919D559F58756e395079cb4f8bbF826, 0xE0129Dfa21d845452285bc72332C175dcabC3Adc, 0xe0d1Bfc466761FAAa5C79fdA936F0565Fd10ED76, 0xe0dA3a00D6378aD8D3D143b3c5cC8183A88f587c, 0xe19A98c174fE6bdD2D4e6Bb602cc1D72932501c8, 0xE21eD5251B2Bd025ad9DFEb32f73f53Cf7ccb927, 0xe275325f697201Ce25a257C0815e3fe04E72aF58, 0xE37582Cb7ae307196D6e789b7F8CCB665D34ac77, 0xE43840e77829B2dF75959B7107D172060Ab6bd87, 0xE4421b63C1501659e567EB8b51EE5e276763705e, 0xe74020F317C8b681ae7FFA64AA0811366D585E1F, 0xe7a62B99fB32654bDD4E144E0a6CB9507FA843fF, 0xE873e5be9E147735f2c116071aF328197A24CE1A, 0xE8caDEdf0A7b0F0e6b23C657Ab1e1C857c8EA404, 0xE934AEeC5f84C1eedDc615489F39960947C07186, 0xeA027e8c565c981ec6918efa4B26474831ee2e88, 0xEa8490b7c0FC94950798e73C88d0FEf18bD45BCA, 0xEB0EbBc451218551F4152Db2887faF6c8BBA7BC0, 0xeB614A685017dd18610D0A5b2bAa1b14123a5Ac2, 0xeb8ee9b48CbE8D900D58A6ac496960e8E6880AcC, 0xeBB51549bA3ea57CE52b60899edA9A97959Bd578, 0xeC2A9A192929ed1f280f7Fd8935b881e3a649dc0, 0xEcEcafB3feA380eD39264a7aC86A3af846375aFF, 0xED1A4812a6Efc061959045076ac088E5C5E4182a, 0xED271cb525759A85910CC0518E126B80ccb66b46, 0xeD82a48C862d128f17005F12adA4aa66eEaE874b, 0xEdba5d56d0147aee8a227D284bcAaC03B4a87eD4, 0xEE38b0CD6e164cafa1e655D8C8E585bA5Efd61B8, 0xee5280e9eb7B9d33cA03332Db7382b24F4A2D009, 0xeea89C8843E8BEb56e411bb4CAc6DBc2d937eE1d, 0xEf6F400f46ea2B289B226F610d851A8324B67974, 0xF052482E025a056146d903a8802d04e7328543F5, 0xF05F0A21310A6Ac0c8379E3c05f904A184E02Eb3, 0xf0B33cEAfab33F5e00A86d74165e21e7b8a75fCA, 0xF18C3e4a9cD0Aea19Cc37AC159f3B1BAdDec9B9E, 0xf25E635a9f35c97df49C52637EdDCDcA64259EF8, 0xf3288AF248DCcA5fBb1F740d6f89f48dAC6238E6, 0xF392824e68017978b754c3B19580937BA6a27B67, 0xf3EA2055F49938ec338A913ABeCEdBb3451A37fE, 0xf48578E2Fdf3B098Bf0C6c4A5DD1E023C47bf04c, 0xf5493d28b94521fe392F640aA78df3C68531964e, 0xF5637Bfc651A33b4ecc10826F89839e564A41443, 0xf585911aef9ab39C9f6B15405dF557e484b312a5, 0xf5dCb2a47f738d8bA39F9Fa2DdC7592f268a262A, 0xF6Aa12C07d271e079859EC7D1Fca34694eD7a7a1, 0xF6c8D0b788d97c8DC63186F99aABB76eC27977BE, 0xf7200f7a475b53446A10421DEa95299fA9319A85, 0xf7cA06A65DeE26fFaabC8DA94a892714D874D13F, 0xFc541Cd48E0795F042cc58DD730923fCd099e31D, 0xFCcb964C514C12794509ed62fa274f0E284ceE82, 0xfdfd08C6A3fDfda9324b9AeFBB5E11207d26C934, 0xFeE16F131dB7B0d4cDb8dA3Be2AFB5e63A58c8a0, 0xff0f4BD4C247D58335663B81aD54D7543661D1fc, 0xff4F2c41Af6BAc672164357677466Ded6B92dac0];
    //Founders Series Owners
    //The starting address wins a Callaway. The remaining are distributed sequentially to the addresses in the 'addresses' array to the right of the starting address. If the end of the array is reached, then it wraps around to the start of the array until available NFTs are exhausted.
    address public startingAddress;
    uint public totalCallawaysAwarded = 5;

    constructor() 
        VRFConsumerBase(
            vrfCoordinator,
            linkToken
        ) public
    {
        contractOwner = msg.sender;
    }
    
    modifier onlyOwner() {
        require(msg.sender == contractOwner, "Only the owner of the contract may call this function.");
        _;
    }
    
    modifier contractAlive() {
        require(permanentlyStop == false, "The contract is no longer accepting VRF requests.");
        _;
    }
    
    modifier coordinatorAllowed() {
        require(coordinatorBlocked == false, "The VRF Coordinator is no longer allowed to call this function.");
        _;
    }
    
    function getRandomNumber() public onlyOwner contractAlive {
        require(LINK.balanceOf(address(this)) >= fee, "Not enough LINK to pay the coordinator.");
        requestRandomness(keyHash, fee);
        permanentlyStop = true;
    }

    //When the Chainlink VRF Coordinator calls back with the random number the information is permanently stored in the variables since the contract is single use.
    function fulfillRandomness(bytes32 requestId, uint256 randomNumber) internal override coordinatorAllowed {
        require(msg.sender == vrfCoordinator, "Only the VRF Coordinator may call this function.");
        requestIDGenerated = requestId;
        //Take only the last 12 digits. It's enough to eliminate modulo bias.
        randomNumberGenerated = randomNumber % 10 ** 12 % addresses.length;
        startingAddress = addresses[randomNumberGenerated];
        coordinatorBlocked = true;
    }
}