/**
 *Submitted for verification at polygonscan.com on 2023-07-09
*/

pragma solidity >=0.7.0 <0.9.0;
// SPDX-License-Identifier: MIT

/**
 * Generated by : https://www.cues.sg
 * Cues.sg : We make technology accessible.
 * Contract Type : ERC20 Minting
 * Referral Scheme : 15.0
 * Referral Scheme : 15.0
 * Referral Scheme : 20.0
*/

// OpenZeppelin Contracts v4.4.1 (token/ERC20/ERC20.sol)

/**
 * @dev Provides information about the current execution context, including the
 * sender of the transaction and its data. While these are generally available
 * via msg.sender and msg.data, they should not be accessed in such a direct
 * manner, since when dealing with meta-transactions the account sending and
 * paying for execution may not be the actual sender (as far as an application
 * is concerned).
 *
 * This contract is only required for intermediate, library-like contracts.
 */
abstract contract Context {
	function _msgSender() internal view virtual returns (address) {
		return msg.sender;
	}

	function _msgData() internal view virtual returns (bytes calldata) {
		return msg.data;
	}
}

/**
 * @dev Interface of the ERC20 standard as defined in the EIP.
 */
interface IERC20 {
	/**
	 * @dev Returns the amount of tokens in existence.
	 */
	function totalSupply() external view returns (uint256);

	/**
	 * @dev Returns the amount of tokens owned by `account`.
	 */
	function balanceOf(address account) external view returns (uint256);

	/**
	 * @dev Moves `amount` tokens from the caller's account to `recipient`.
	 *
	 * Returns a boolean value indicating whether the operation succeeded.
	 *
	 * Emits a {Transfer} event.
	 */
	function transfer(address recipient, uint256 amount) external returns (bool);

	/**
	 * @dev Returns the remaining number of tokens that `spender` will be
	 * allowed to spend on behalf of `owner` through {transferFrom}. This is
	 * zero by default.
	 *
	 * This value changes when {approve} or {transferFrom} are called.
	 */
	function allowance(address owner, address spender) external view returns (uint256);

	/**
	 * @dev Sets `amount` as the allowance of `spender` over the caller's tokens.
	 *
	 * Returns a boolean value indicating whether the operation succeeded.
	 *
	 * IMPORTANT: Beware that changing an allowance with this method brings the risk
	 * that someone may use both the old and the new allowance by unfortunate
	 * transaction ordering. One possible solution to mitigate this race
	 * condition is to first reduce the spender's allowance to 0 and set the
	 * desired value afterwards:
	 * https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
	 *
	 * Emits an {Approval} event.
	 */
	function approve(address spender, uint256 amount) external returns (bool);

	/**
	 * @dev Moves `amount` tokens from `sender` to `recipient` using the
	 * allowance mechanism. `amount` is then deducted from the caller's
	 * allowance.
	 *
	 * Returns a boolean value indicating whether the operation succeeded.
	 *
	 * Emits a {Transfer} event.
	 */
	function transferFrom(
		address sender,
		address recipient,
		uint256 amount
	) external returns (bool);

	/**
	 * @dev Emitted when `value` tokens are moved from one account (`from`) to
	 * another (`to`).
	 *
	 * Note that `value` may be zero.
	 */
	event Transfer(address indexed from, address indexed to, uint256 value);

	/**
	 * @dev Emitted when the allowance of a `spender` for an `owner` is set by
	 * a call to {approve}. `value` is the new allowance.
	 */
	event Approval(address indexed owner, address indexed spender, uint256 value);
}

/**
 * @dev Implementation of the {IERC20} interface.
 *
 * This implementation is agnostic to the way tokens are created. This means
 * that a supply mechanism has to be added in a derived contract using {_mint}.
 * For a generic mechanism see {ERC20PresetMinterPauser}.
 *
 * TIP: For a detailed writeup see our guide
 * https://forum.zeppelin.solutions/t/how-to-implement-erc20-supply-mechanisms/226[How
 * to implement supply mechanisms].
 *
 * We have followed general OpenZeppelin Contracts guidelines: functions revert
 * instead returning `false` on failure. This behavior is nonetheless
 * conventional and does not conflict with the expectations of ERC20
 * applications.
 *
 * Additionally, an {Approval} event is emitted on calls to {transferFrom}.
 * This allows applications to reconstruct the allowance for all accounts just
 * by listening to said events. Other implementations of the EIP may not emit
 * these events, as it isn't required by the specification.
 *
 * Finally, the non-standard {decreaseAllowance} and {increaseAllowance}
 * functions have been added to mitigate the well-known issues around setting
 * allowances. See {IERC20-approve}.
 */



/**
 * @dev Interface for the optional metadata functions from the ERC20 standard.
 *
 * _Available since v4.1._
 */
interface IERC20Metadata is IERC20 {
	/**
	 * @dev Returns the name of the token.
	 */
	function name() external view returns (string memory);

	/**
	 * @dev Returns the symbol of the token.
	 */
	function symbol() external view returns (string memory);

	/**
	 * @dev Returns the decimals places of the token.
	 */
	function decimals() external view returns (uint8);
}


contract ERC20 is Context, IERC20, IERC20Metadata {
	mapping(address => uint256) private _balances;

	mapping(address => mapping(address => uint256)) private _allowances;

	uint256 private _totalSupply;

	string private _name;
	string private _symbol;

	/**
	 * @dev Sets the values for {name} and {symbol}.
	 *
	 * The default value of {decimals} is 18. To select a different value for
	 * {decimals} you should overload it.
	 *
	 * All two of these values are immutable: they can only be set once during
	 * construction.
	 */
	constructor(string memory name_, string memory symbol_) {
		_name = name_;
		_symbol = symbol_;
	}

	/**
	 * @dev Returns the name of the token.
	 */
	function name() public view virtual override returns (string memory) {
		return _name;
	}

	/**
	 * @dev Returns the symbol of the token, usually a shorter version of the
	 * name.
	 */
	function symbol() public view virtual override returns (string memory) {
		return _symbol;
	}

	/**
	 * @dev Returns the number of decimals used to get its user representation.
	 * For example, if `decimals` equals `2`, a balance of `505` tokens should
	 * be displayed to a user as `5.05` (`505 / 10 ** 2`).
	 *
	 * Tokens usually opt for a value of 18, imitating the relationship between
	 * Ether and Wei. This is the value {ERC20} uses, unless this function is
	 * overridden;
	 *
	 * NOTE: This information is only used for _display_ purposes: it in
	 * no way affects any of the arithmetic of the contract, including
	 * {IERC20-balanceOf} and {IERC20-transfer}.
	 */
	function decimals() public view virtual override returns (uint8) {
		return 18;
	}

	/**
	 * @dev See {IERC20-totalSupply}.
	 */
	function totalSupply() public view virtual override returns (uint256) {
		return _totalSupply;
	}

	/**
	 * @dev See {IERC20-balanceOf}.
	 */
	function balanceOf(address account) public view virtual override returns (uint256) {
		return _balances[account];
	}

	/**
	 * @dev See {IERC20-transfer}.
	 *
	 * Requirements:
	 *
	 * - `recipient` cannot be the zero address.
	 * - the caller must have a balance of at least `amount`.
	 */
	function transfer(address recipient, uint256 amount) public virtual override returns (bool) {
		_transfer(_msgSender(), recipient, amount);
		return true;
	}

	/**
	 * @dev See {IERC20-allowance}.
	 */
	function allowance(address owner, address spender) public view virtual override returns (uint256) {
		return _allowances[owner][spender];
	}

	/**
	 * @dev See {IERC20-approve}.
	 *
	 * Requirements:
	 *
	 * - `spender` cannot be the zero address.
	 */
	function approve(address spender, uint256 amount) public virtual override returns (bool) {
		_approve(_msgSender(), spender, amount);
		return true;
	}

	/**
	 * @dev See {IERC20-transferFrom}.
	 *
	 * Emits an {Approval} event indicating the updated allowance. This is not
	 * required by the EIP. See the note at the beginning of {ERC20}.
	 *
	 * Requirements:
	 *
	 * - `sender` and `recipient` cannot be the zero address.
	 * - `sender` must have a balance of at least `amount`.
	 * - the caller must have allowance for ``sender``'s tokens of at least
	 * `amount`.
	 */
	function transferFrom(
		address sender,
		address recipient,
		uint256 amount
	) public virtual override returns (bool) {
		_transfer(sender, recipient, amount);

		uint256 currentAllowance = _allowances[sender][_msgSender()];
		require(currentAllowance >= amount, "ERC20: transfer amount exceeds allowance");
		unchecked {
			_approve(sender, _msgSender(), currentAllowance - amount);
		}

		return true;
	}

	/**
	 * @dev Atomically increases the allowance granted to `spender` by the caller.
	 *
	 * This is an alternative to {approve} that can be used as a mitigation for
	 * problems described in {IERC20-approve}.
	 *
	 * Emits an {Approval} event indicating the updated allowance.
	 *
	 * Requirements:
	 *
	 * - `spender` cannot be the zero address.
	 */
	function increaseAllowance(address spender, uint256 addedValue) public virtual returns (bool) {
		_approve(_msgSender(), spender, _allowances[_msgSender()][spender] + addedValue);
		return true;
	}

	/**
	 * @dev Atomically decreases the allowance granted to `spender` by the caller.
	 *
	 * This is an alternative to {approve} that can be used as a mitigation for
	 * problems described in {IERC20-approve}.
	 *
	 * Emits an {Approval} event indicating the updated allowance.
	 *
	 * Requirements:
	 *
	 * - `spender` cannot be the zero address.
	 * - `spender` must have allowance for the caller of at least
	 * `subtractedValue`.
	 */
	function decreaseAllowance(address spender, uint256 subtractedValue) public virtual returns (bool) {
		uint256 currentAllowance = _allowances[_msgSender()][spender];
		require(currentAllowance >= subtractedValue, "ERC20: decreased allowance below zero");
		unchecked {
			_approve(_msgSender(), spender, currentAllowance - subtractedValue);
		}

		return true;
	}

	/**
	 * @dev Moves `amount` of tokens from `sender` to `recipient`.
	 *
	 * This internal function is equivalent to {transfer}, and can be used to
	 * e.g. implement automatic token fees, slashing mechanisms, etc.
	 *
	 * Emits a {Transfer} event.
	 *
	 * Requirements:
	 *
	 * - `sender` cannot be the zero address.
	 * - `recipient` cannot be the zero address.
	 * - `sender` must have a balance of at least `amount`.
	 */
	function _transfer(
		address sender,
		address recipient,
		uint256 amount
	) internal virtual {
		require(sender != address(0), "ERC20: transfer from the zero address");
		require(recipient != address(0), "ERC20: transfer to the zero address");

		_beforeTokenTransfer(sender, recipient, amount);

		uint256 senderBalance = _balances[sender];
		require(senderBalance >= amount, "ERC20: transfer amount exceeds balance");
		unchecked {
			_balances[sender] = senderBalance - amount;
		}
		_balances[recipient] += amount;

		emit Transfer(sender, recipient, amount);

		_afterTokenTransfer(sender, recipient, amount);
	}

	/** @dev Creates `amount` tokens and assigns them to `account`, increasing
	 * the total supply.
	 *
	 * Emits a {Transfer} event with `from` set to the zero address.
	 *
	 * Requirements:
	 *
	 * - `account` cannot be the zero address.
	 */
	function _mint(address account, uint256 amount) internal virtual {
		require(account != address(0), "ERC20: mint to the zero address");

		_beforeTokenTransfer(address(0), account, amount);

		_totalSupply += amount;
		_balances[account] += amount;
		emit Transfer(address(0), account, amount);

		_afterTokenTransfer(address(0), account, amount);
	}

	/**
	 * @dev Destroys `amount` tokens from `account`, reducing the
	 * total supply.
	 *
	 * Emits a {Transfer} event with `to` set to the zero address.
	 *
	 * Requirements:
	 *
	 * - `account` cannot be the zero address.
	 * - `account` must have at least `amount` tokens.
	 */
	function _burn(address account, uint256 amount) internal virtual {
		require(account != address(0), "ERC20: burn from the zero address");

		_beforeTokenTransfer(account, address(0), amount);

		uint256 accountBalance = _balances[account];
		require(accountBalance >= amount, "ERC20: burn amount exceeds balance");
		unchecked {
			_balances[account] = accountBalance - amount;
		}
		_totalSupply -= amount;

		emit Transfer(account, address(0), amount);

		_afterTokenTransfer(account, address(0), amount);
	}

	/**
	 * @dev Sets `amount` as the allowance of `spender` over the `owner` s tokens.
	 *
	 * This internal function is equivalent to `approve`, and can be used to
	 * e.g. set automatic allowances for certain subsystems, etc.
	 *
	 * Emits an {Approval} event.
	 *
	 * Requirements:
	 *
	 * - `owner` cannot be the zero address.
	 * - `spender` cannot be the zero address.
	 */
	function _approve(
		address owner,
		address spender,
		uint256 amount
	) internal virtual {
		require(owner != address(0), "ERC20: approve from the zero address");
		require(spender != address(0), "ERC20: approve to the zero address");

		_allowances[owner][spender] = amount;
		emit Approval(owner, spender, amount);
	}

	/**
	 * @dev Hook that is called before any transfer of tokens. This includes
	 * minting and burning.
	 *
	 * Calling conditions:
	 *
	 * - when `from` and `to` are both non-zero, `amount` of ``from``'s tokens
	 * will be transferred to `to`.
	 * - when `from` is zero, `amount` tokens will be minted for `to`.
	 * - when `to` is zero, `amount` of ``from``'s tokens will be burned.
	 * - `from` and `to` are never both zero.
	 *
	 * To learn more about hooks, head to xref:ROOT:extending-contracts.adoc#using-hooks[Using Hooks].
	 */
	function _beforeTokenTransfer(
		address from,
		address to,
		uint256 amount
	) internal virtual {}

	/**
	 * @dev Hook that is called after any transfer of tokens. This includes
	 * minting and burning.
	 *
	 * Calling conditions:
	 *
	 * - when `from` and `to` are both non-zero, `amount` of ``from``'s tokens
	 * has been transferred to `to`.
	 * - when `from` is zero, `amount` tokens have been minted for `to`.
	 * - when `to` is zero, `amount` of ``from``'s tokens have been burned.
	 * - `from` and `to` are never both zero.
	 *
	 * To learn more about hooks, head to xref:ROOT:extending-contracts.adoc#using-hooks[Using Hooks].
	 */
	function _afterTokenTransfer(
		address from,
		address to,
		uint256 amount
	) internal virtual {}
}

contract Coin_STARP is ERC20 {

	address owner;
	event Burn (address indexed account);
	event Mint (address indexed mintBy);
	bool public enableMintPhase1 = true;
	bool public enableMintPhase2 = true;
	bool public enableMintPhase3 = true;
	uint256 public mint1c0_e9964279Price = uint256(111000000000);
	event mint1c0_e9964279NewPrice (uint256 newPrice);
	uint256 public mint1_StarTokenAmtInBank = uint256(0);
	uint256 public mint2c0_d8001382Price = uint256(333000000000000000000);
	event mint2c0_d8001382NewPrice (uint256 newPrice);
	uint256 public mint2_StarTokenV2AmtInBank = uint256(0);
	uint256 public mint3c0_a6d455daPrice = uint256(77000000000000000000);
	event mint3c0_a6d455daNewPrice (uint256 newPrice);
	uint256 public mint3_DAOAmtInBank = uint256(0);
	struct referralRecord { bool hasDeposited; address referringAddress; uint256 unclaimedRewards1InStarToken; uint256 unclaimedRewards2InStarTokenV2; uint256 unclaimedRewards3InDAO; uint256 referralsAmt1AtLevel0; uint256 referralsCount1AtLevel0; uint256 referralsAmt2AtLevel0; uint256 referralsCount2AtLevel0; uint256 referralsAmt3AtLevel0; uint256 referralsCount3AtLevel0; }
	mapping(address => referralRecord) public referralRecordMap;
	event ReferralAddressAdded (address indexed referredAddress);
	uint256 public totalUnclaimedRewards1InStarToken = uint256(0);
	uint256 public totalClaimedRewards1InStarToken = uint256(0);
	uint256 public totalUnclaimedRewards2InStarTokenV2 = uint256(0);
	uint256 public totalClaimedRewards2InStarTokenV2 = uint256(0);
	uint256 public totalUnclaimedRewards3InDAO = uint256(0);
	uint256 public totalClaimedRewards3InDAO = uint256(0);
	uint256 public transferTaxAmt0 = uint256(110000);
	address public transferTaxAddress0 = address(0xBDCBD23316AAA2aDecA774e107868adCE38cC69E);
	address[] public transferTaxExclusionList0;
	address[] public burnExclusionList;

	constructor() ERC20("STARPower", "STARP") {
		owner = 0xBDCBD23316AAA2aDecA774e107868adCE38cC69E;
		super._mint(address(0xBDCBD23316AAA2aDecA774e107868adCE38cC69E), uint256(10000000000000000000000000));
	}

	//This function allows the owner to specify an address that will take over ownership rights instead. Please double check the address provided as once the function is executed, only the new owner will be able to change the address back.
	function changeOwner(address _newOwner) public onlyOwner {
		owner = _newOwner;
	}

	modifier onlyOwner() {
		require(msg.sender == owner);
		_;
	}

	function isInside_address(address _j0, address[] memory _j1) internal pure returns (bool){
		for (uint _i = 0; _i < _j1.length; _i++){
			if (_j0 == _j1[_i]){
				return true;
			}
		}
		return false;
	}

/**
 * Function changeValueOf_enableMintPhase1
 * Notes for _enableMintPhase1 : Set true to enable mint phase 1, false to disable.
 * The function takes in 1 variable, (a boolean) _enableMintPhase1. It can only be called by functions outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates enableMintPhase1 as _enableMintPhase1
*/
	function changeValueOf_enableMintPhase1(bool _enableMintPhase1) external onlyOwner {
		enableMintPhase1  = _enableMintPhase1;
	}

/**
 * Function changeValueOf_enableMintPhase2
 * Notes for _enableMintPhase2 : Set true to enable mint phase 2, false to disable.
 * The function takes in 1 variable, (a boolean) _enableMintPhase2. It can only be called by functions outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates enableMintPhase2 as _enableMintPhase2
*/
	function changeValueOf_enableMintPhase2(bool _enableMintPhase2) external onlyOwner {
		enableMintPhase2  = _enableMintPhase2;
	}

/**
 * Function changeValueOf_enableMintPhase3
 * Notes for _enableMintPhase3 : Set true to enable mint phase 3, false to disable.
 * The function takes in 1 variable, (a boolean) _enableMintPhase3. It can only be called by functions outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates enableMintPhase3 as _enableMintPhase3
*/
	function changeValueOf_enableMintPhase3(bool _enableMintPhase3) external onlyOwner {
		enableMintPhase3  = _enableMintPhase3;
	}

/**
 * Function changeValueOf_transferTaxAmt0
 * Notes for _transferTaxAmt0 : 1 percent is represented by 10000.
 * The function takes in 1 variable, (zero or a positive integer) _transferTaxAmt0. It can only be called by functions outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates transferTaxAmt0 as _transferTaxAmt0
*/
	function changeValueOf_transferTaxAmt0(uint256 _transferTaxAmt0) external onlyOwner {
		transferTaxAmt0  = _transferTaxAmt0;
	}

/**
 * Function changeValueOf_transferTaxAddress0
 * Notes for _transferTaxAddress0 : Set address to pass tax to.
 * The function takes in 1 variable, (an address) _transferTaxAddress0. It can only be called by functions outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates transferTaxAddress0 as _transferTaxAddress0
*/
	function changeValueOf_transferTaxAddress0(address _transferTaxAddress0) external onlyOwner {
		transferTaxAddress0  = _transferTaxAddress0;
	}

/**
 * Function transfer
 * The function takes in 2 variables, (an address) receipient, and (zero or a positive integer) _amount. It can be called by functions both inside and outside of this contract. It does the following :
 * creates an internal variable taxAmt with initial value 0
 * if check if (the address that called this function) is inside burnExclusionList then it does nothing else otherwise (calls super._burn with variable account as (the address that called this function), variable amount as (((_amount) * (22)) / (100)); and then updates taxAmt as (taxAmt) + (((_amount) * (22)) / (100)))
 * if check if (the address that called this function) is inside transferTaxExclusionList0 then it does nothing else otherwise (calls super.transfer with variable receipient as transferTaxAddress0, variable amount as (((_amount) * (transferTaxAmt0)) / (1000000)); and then updates taxAmt as (((_amount) * (transferTaxAmt0)) / (1000000)) + (taxAmt))
 * calls super.transfer with variable receipient as receipient, variable amount as ((_amount) - (taxAmt))
 * returns true as output
 * This function overrides the original transfer.
*/
	function transfer(address receipient, uint256 _amount) public override returns (bool) {
		uint256 taxAmt = uint256(0);
		if (isInside_address(msg.sender, burnExclusionList)){
		}else{
			super._burn(msg.sender, ((_amount * uint256(22)) / uint256(100)));
			taxAmt  = (taxAmt + ((_amount * uint256(22)) / uint256(100)));
		}
		if (isInside_address(msg.sender, transferTaxExclusionList0)){
		}else{
			super.transfer(transferTaxAddress0, ((_amount * transferTaxAmt0) / uint256(1000000)));
			taxAmt  = (((_amount * transferTaxAmt0) / uint256(1000000)) + taxAmt);
		}
		super.transfer(receipient, (_amount - taxAmt));
		return true;
	}

/**
 * Function addToBurnExclusionList
 * The function takes in 1 variable, (an address) _addressToAdd. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * if check if _addressToAdd is inside burnExclusionList then it does nothing else otherwise (adds _addressToAdd to burnExclusionList)
*/
	function addToBurnExclusionList(address _addressToAdd) public onlyOwner {
		if (isInside_address(_addressToAdd, burnExclusionList)){
		}else{
			burnExclusionList.push(_addressToAdd);
		}
	}

/**
 * Function removeFromBurnExclusionList
 * The function takes in 1 variable, (an address) _addressToAdd. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * if check if _addressToAdd is inside burnExclusionList then (repeat length of burnExclusionList times with loop variable i0 :  (if _addressToAdd is equals to (burnExclusionList with element (Loop Variable i0) - (1)) then (if (length of burnExclusionList) is strictly greater than (Loop Variable i0) then (updates burnExclusionList (Element (Loop Variable i0) - (1)) as burnExclusionList with element (length of burnExclusionList) - (1)); and then removes last item from burnExclusionList)))
*/
	function removeFromBurnExclusionList(address _addressToAdd) public onlyOwner {
		if (isInside_address(_addressToAdd, burnExclusionList)){
			for (uint i0 = (burnExclusionList).length; i0 > 0; i0--){
				if ((_addressToAdd == burnExclusionList[(i0 - uint256(1))])){
					if (((burnExclusionList).length > i0)){
						burnExclusionList[(i0 - uint256(1))]  = burnExclusionList[((burnExclusionList).length - uint256(1))];
					}
					burnExclusionList.pop();
				}
			}
		}
	}

/**
 * Function mint1
 * Notes for _amt : Specify 1 coin here as 10^18
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that enableMintPhase1
 * checks that ((totalSupply) + (_amt)) is less than or equals to 1000000000000000000000000000
 * creates an internal variable referralAllocationInStarToken with initial value addReferral1 with variable _amt as _amt
 * calls ERC20(Address 0x8440178087C4fd348D43d0205F4574e0348a06F0)'s at transferFrom function  with variable sender as (the address that called this function), variable recipient as (the address of this contract), variable amount as (((mint1c0_e9964279Price) * (_amt)) / (10 raised to the power of 18))
 * updates mint1_StarTokenAmtInBank as (mint1_StarTokenAmtInBank) + ((((mint1c0_e9964279Price) * (_amt)) / (10 raised to the power of 18)) - (referralAllocationInStarToken))
 * calls super._mint with variable account as (the address that called this function), variable amount as _amt
 * emits event Mint with inputs the address that called this function
*/
	function mint1(uint256 _amt) public {
		require(enableMintPhase1, "Mint Phase 1 not enabled");
		require(((totalSupply() + _amt) <= uint256(1000000000000000000000000000)), "Exceeded Total Supply");
		uint256 referralAllocationInStarToken = addReferral1(_amt);
		ERC20(address(0x8440178087C4fd348D43d0205F4574e0348a06F0)).transferFrom(msg.sender, address(this), ((mint1c0_e9964279Price * uint256(_amt)) / (uint256(10) ** uint256(18))));
		mint1_StarTokenAmtInBank  = (mint1_StarTokenAmtInBank + (((mint1c0_e9964279Price * uint256(_amt)) / (uint256(10) ** uint256(18))) - referralAllocationInStarToken));
		super._mint(msg.sender, _amt);
		emit Mint(msg.sender);
	}

/**
 * Function mint2
 * Notes for _amt : Specify 1 coin here as 10^18
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that enableMintPhase2
 * checks that ((totalSupply) + (_amt)) is less than or equals to 1000000000000000000000000000
 * creates an internal variable referralAllocationInStarTokenV2 with initial value addReferral2 with variable _amt as _amt
 * calls ERC20(Address 0xD289c01528921B5f6D5B111a50a99456D495bF78)'s at transferFrom function  with variable sender as (the address that called this function), variable recipient as (the address of this contract), variable amount as (((mint2c0_d8001382Price) * (_amt)) / (10 raised to the power of 18))
 * updates mint2_StarTokenV2AmtInBank as (mint2_StarTokenV2AmtInBank) + ((((mint2c0_d8001382Price) * (_amt)) / (10 raised to the power of 18)) - (referralAllocationInStarTokenV2))
 * calls super._mint with variable account as (the address that called this function), variable amount as _amt
 * emits event Mint with inputs the address that called this function
*/
	function mint2(uint256 _amt) public {
		require(enableMintPhase2, "Mint Phase 2 not enabled");
		require(((totalSupply() + _amt) <= uint256(1000000000000000000000000000)), "Exceeded Total Supply");
		uint256 referralAllocationInStarTokenV2 = addReferral2(_amt);
		ERC20(address(0xD289c01528921B5f6D5B111a50a99456D495bF78)).transferFrom(msg.sender, address(this), ((mint2c0_d8001382Price * uint256(_amt)) / (uint256(10) ** uint256(18))));
		mint2_StarTokenV2AmtInBank  = (mint2_StarTokenV2AmtInBank + (((mint2c0_d8001382Price * uint256(_amt)) / (uint256(10) ** uint256(18))) - referralAllocationInStarTokenV2));
		super._mint(msg.sender, _amt);
		emit Mint(msg.sender);
	}

/**
 * Function mint3
 * Notes for _amt : Specify 1 coin here as 10^18
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that enableMintPhase3
 * checks that ((totalSupply) + (_amt)) is less than or equals to 1000000000000000000000000000
 * creates an internal variable referralAllocationInDAO with initial value addReferral3 with variable _amt as _amt
 * calls ERC20(Address 0x17840DF7CAa07e298b16E8612157B90ED231C973)'s at transferFrom function  with variable sender as (the address that called this function), variable recipient as (the address of this contract), variable amount as (((mint3c0_a6d455daPrice) * (_amt)) / (10 raised to the power of 18))
 * updates mint3_DAOAmtInBank as (mint3_DAOAmtInBank) + ((((mint3c0_a6d455daPrice) * (_amt)) / (10 raised to the power of 18)) - (referralAllocationInDAO))
 * calls super._mint with variable account as (the address that called this function), variable amount as _amt
 * emits event Mint with inputs the address that called this function
*/
	function mint3(uint256 _amt) public {
		require(enableMintPhase3, "Mint Phase 3 not enabled");
		require(((totalSupply() + _amt) <= uint256(1000000000000000000000000000)), "Exceeded Total Supply");
		uint256 referralAllocationInDAO = addReferral3(_amt);
		ERC20(address(0x17840DF7CAa07e298b16E8612157B90ED231C973)).transferFrom(msg.sender, address(this), ((mint3c0_a6d455daPrice * uint256(_amt)) / (uint256(10) ** uint256(18))));
		mint3_DAOAmtInBank  = (mint3_DAOAmtInBank + (((mint3c0_a6d455daPrice * uint256(_amt)) / (uint256(10) ** uint256(18))) - referralAllocationInDAO));
		super._mint(msg.sender, _amt);
		emit Mint(msg.sender);
	}

/**
 * Function change_mint1c0_e9964279Price
 * The function takes in 1 variable, (zero or a positive integer) _newPrice. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates mint1c0_e9964279Price as _newPrice
 * emits event mint1c0_e9964279NewPrice with inputs _newPrice
*/
	function change_mint1c0_e9964279Price(uint256 _newPrice) public onlyOwner {
		mint1c0_e9964279Price  = _newPrice;
		emit mint1c0_e9964279NewPrice(_newPrice);
	}

/**
 * Function withdrawReferral1InStarToken
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that (referralRecordMap with element the address that called this function with element unclaimedRewards1InStarToken) is greater than or equals to _amt
 * updates referralRecordMap (Element the address that called this function) (Entity unclaimedRewards1InStarToken) as (referralRecordMap with element the address that called this function with element unclaimedRewards1InStarToken) - (_amt)
 * updates totalUnclaimedRewards1InStarToken as (totalUnclaimedRewards1InStarToken) - (_amt)
 * updates totalClaimedRewards1InStarToken as (totalClaimedRewards1InStarToken) + (_amt)
 * checks that (ERC20(Address 0x8440178087C4fd348D43d0205F4574e0348a06F0)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to _amt
 * if _amt is strictly greater than 0 then (calls ERC20(Address 0x8440178087C4fd348D43d0205F4574e0348a06F0)'s at transfer function  with variable recipient as (the address that called this function), variable amount as _amt)
*/
	function withdrawReferral1InStarToken(uint256 _amt) public {
		require((referralRecordMap[msg.sender].unclaimedRewards1InStarToken >= _amt), "Insufficient referral rewards to withdraw");
		referralRecordMap[msg.sender].unclaimedRewards1InStarToken  = (referralRecordMap[msg.sender].unclaimedRewards1InStarToken - _amt);
		totalUnclaimedRewards1InStarToken  = (totalUnclaimedRewards1InStarToken - _amt);
		totalClaimedRewards1InStarToken  = (totalClaimedRewards1InStarToken + _amt);
		require((ERC20(address(0x8440178087C4fd348D43d0205F4574e0348a06F0)).balanceOf(address(this)) >= _amt), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((_amt > uint256(0))){
			ERC20(address(0x8440178087C4fd348D43d0205F4574e0348a06F0)).transfer(msg.sender, _amt);
		}
	}

/**
 * Function addReferral1
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can only be called by other functions in this contract. It does the following :
 * creates an internal variable referringAddress with initial value referralRecordMap with element the address that called this function with element referringAddress
 * creates an internal variable referralsAllocatedInStarToken with initial value 0
 * if not referralRecordMap with element the address that called this function with element hasDeposited then (updates referralRecordMap (Element the address that called this function) (Entity hasDeposited) as true)
 * if referringAddress is equals to Address 0 then (returns referralsAllocatedInStarToken as output)
 * updates referralRecordMap (Element referringAddress) (Entity referralsAmt1AtLevel0) as (referralRecordMap with element referringAddress with element referralsAmt1AtLevel0) + (_amt)
 * updates referralRecordMap (Element referringAddress) (Entity referralsCount1AtLevel0) as (referralRecordMap with element referringAddress with element referralsCount1AtLevel0) + (1)
 * updates referralRecordMap (Element referringAddress) (Entity unclaimedRewards1InStarToken) as (referralRecordMap with element referringAddress with element unclaimedRewards1InStarToken) + (((15) * (_amt)) / (100))
 * updates referralsAllocatedInStarToken as (referralsAllocatedInStarToken) + (((15) * (_amt)) / (100))
 * updates referringAddress as referralRecordMap with element referringAddress with element referringAddress
 * updates totalUnclaimedRewards1InStarToken as (totalUnclaimedRewards1InStarToken) + (referralsAllocatedInStarToken)
 * returns referralsAllocatedInStarToken as output
*/
	function addReferral1(uint256 _amt) internal returns (uint256) {
		address referringAddress = referralRecordMap[msg.sender].referringAddress;
		uint256 referralsAllocatedInStarToken = uint256(0);
		if (!(referralRecordMap[msg.sender].hasDeposited)){
			referralRecordMap[msg.sender].hasDeposited  = true;
		}
		if ((referringAddress == address(0))){
			return referralsAllocatedInStarToken;
		}
		referralRecordMap[referringAddress].referralsAmt1AtLevel0  = (referralRecordMap[referringAddress].referralsAmt1AtLevel0 + _amt);
		referralRecordMap[referringAddress].referralsCount1AtLevel0  = (referralRecordMap[referringAddress].referralsCount1AtLevel0 + uint256(1));
		referralRecordMap[referringAddress].unclaimedRewards1InStarToken  = (referralRecordMap[referringAddress].unclaimedRewards1InStarToken + ((uint256(15) * _amt) / uint256(100)));
		referralsAllocatedInStarToken  = (referralsAllocatedInStarToken + ((uint256(15) * _amt) / uint256(100)));
		referringAddress  = referralRecordMap[referringAddress].referringAddress;
		totalUnclaimedRewards1InStarToken  = (totalUnclaimedRewards1InStarToken + referralsAllocatedInStarToken);
		return referralsAllocatedInStarToken;
	}

/**
 * Function change_mint2c0_d8001382Price
 * The function takes in 1 variable, (zero or a positive integer) _newPrice. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates mint2c0_d8001382Price as _newPrice
 * emits event mint2c0_d8001382NewPrice with inputs _newPrice
*/
	function change_mint2c0_d8001382Price(uint256 _newPrice) public onlyOwner {
		mint2c0_d8001382Price  = _newPrice;
		emit mint2c0_d8001382NewPrice(_newPrice);
	}

/**
 * Function withdrawReferral2InStarTokenV2
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that (referralRecordMap with element the address that called this function with element unclaimedRewards2InStarTokenV2) is greater than or equals to _amt
 * updates referralRecordMap (Element the address that called this function) (Entity unclaimedRewards2InStarTokenV2) as (referralRecordMap with element the address that called this function with element unclaimedRewards2InStarTokenV2) - (_amt)
 * updates totalUnclaimedRewards2InStarTokenV2 as (totalUnclaimedRewards2InStarTokenV2) - (_amt)
 * updates totalClaimedRewards2InStarTokenV2 as (totalClaimedRewards2InStarTokenV2) + (_amt)
 * checks that (ERC20(Address 0xD289c01528921B5f6D5B111a50a99456D495bF78)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to _amt
 * if _amt is strictly greater than 0 then (calls ERC20(Address 0xD289c01528921B5f6D5B111a50a99456D495bF78)'s at transfer function  with variable recipient as (the address that called this function), variable amount as _amt)
*/
	function withdrawReferral2InStarTokenV2(uint256 _amt) public {
		require((referralRecordMap[msg.sender].unclaimedRewards2InStarTokenV2 >= _amt), "Insufficient referral rewards to withdraw");
		referralRecordMap[msg.sender].unclaimedRewards2InStarTokenV2  = (referralRecordMap[msg.sender].unclaimedRewards2InStarTokenV2 - _amt);
		totalUnclaimedRewards2InStarTokenV2  = (totalUnclaimedRewards2InStarTokenV2 - _amt);
		totalClaimedRewards2InStarTokenV2  = (totalClaimedRewards2InStarTokenV2 + _amt);
		require((ERC20(address(0xD289c01528921B5f6D5B111a50a99456D495bF78)).balanceOf(address(this)) >= _amt), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((_amt > uint256(0))){
			ERC20(address(0xD289c01528921B5f6D5B111a50a99456D495bF78)).transfer(msg.sender, _amt);
		}
	}

/**
 * Function addReferral2
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can only be called by other functions in this contract. It does the following :
 * creates an internal variable referringAddress with initial value referralRecordMap with element the address that called this function with element referringAddress
 * creates an internal variable referralsAllocatedInStarTokenV2 with initial value 0
 * if not referralRecordMap with element the address that called this function with element hasDeposited then (updates referralRecordMap (Element the address that called this function) (Entity hasDeposited) as true)
 * if referringAddress is equals to Address 0 then (returns referralsAllocatedInStarTokenV2 as output)
 * updates referralRecordMap (Element referringAddress) (Entity referralsAmt2AtLevel0) as (referralRecordMap with element referringAddress with element referralsAmt2AtLevel0) + (_amt)
 * updates referralRecordMap (Element referringAddress) (Entity referralsCount2AtLevel0) as (referralRecordMap with element referringAddress with element referralsCount2AtLevel0) + (1)
 * updates referralRecordMap (Element referringAddress) (Entity unclaimedRewards2InStarTokenV2) as (referralRecordMap with element referringAddress with element unclaimedRewards2InStarTokenV2) + (((15) * (_amt)) / (100))
 * updates referralsAllocatedInStarTokenV2 as (referralsAllocatedInStarTokenV2) + (((15) * (_amt)) / (100))
 * updates referringAddress as referralRecordMap with element referringAddress with element referringAddress
 * updates totalUnclaimedRewards2InStarTokenV2 as (totalUnclaimedRewards2InStarTokenV2) + (referralsAllocatedInStarTokenV2)
 * returns referralsAllocatedInStarTokenV2 as output
*/
	function addReferral2(uint256 _amt) internal returns (uint256) {
		address referringAddress = referralRecordMap[msg.sender].referringAddress;
		uint256 referralsAllocatedInStarTokenV2 = uint256(0);
		if (!(referralRecordMap[msg.sender].hasDeposited)){
			referralRecordMap[msg.sender].hasDeposited  = true;
		}
		if ((referringAddress == address(0))){
			return referralsAllocatedInStarTokenV2;
		}
		referralRecordMap[referringAddress].referralsAmt2AtLevel0  = (referralRecordMap[referringAddress].referralsAmt2AtLevel0 + _amt);
		referralRecordMap[referringAddress].referralsCount2AtLevel0  = (referralRecordMap[referringAddress].referralsCount2AtLevel0 + uint256(1));
		referralRecordMap[referringAddress].unclaimedRewards2InStarTokenV2  = (referralRecordMap[referringAddress].unclaimedRewards2InStarTokenV2 + ((uint256(15) * _amt) / uint256(100)));
		referralsAllocatedInStarTokenV2  = (referralsAllocatedInStarTokenV2 + ((uint256(15) * _amt) / uint256(100)));
		referringAddress  = referralRecordMap[referringAddress].referringAddress;
		totalUnclaimedRewards2InStarTokenV2  = (totalUnclaimedRewards2InStarTokenV2 + referralsAllocatedInStarTokenV2);
		return referralsAllocatedInStarTokenV2;
	}

/**
 * Function change_mint3c0_a6d455daPrice
 * The function takes in 1 variable, (zero or a positive integer) _newPrice. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * updates mint3c0_a6d455daPrice as _newPrice
 * emits event mint3c0_a6d455daNewPrice with inputs _newPrice
*/
	function change_mint3c0_a6d455daPrice(uint256 _newPrice) public onlyOwner {
		mint3c0_a6d455daPrice  = _newPrice;
		emit mint3c0_a6d455daNewPrice(_newPrice);
	}

/**
 * Function withdrawReferral3InDAO
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that (referralRecordMap with element the address that called this function with element unclaimedRewards3InDAO) is greater than or equals to _amt
 * updates referralRecordMap (Element the address that called this function) (Entity unclaimedRewards3InDAO) as (referralRecordMap with element the address that called this function with element unclaimedRewards3InDAO) - (_amt)
 * updates totalUnclaimedRewards3InDAO as (totalUnclaimedRewards3InDAO) - (_amt)
 * updates totalClaimedRewards3InDAO as (totalClaimedRewards3InDAO) + (_amt)
 * checks that (ERC20(Address 0x17840DF7CAa07e298b16E8612157B90ED231C973)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to _amt
 * if _amt is strictly greater than 0 then (calls ERC20(Address 0x17840DF7CAa07e298b16E8612157B90ED231C973)'s at transfer function  with variable recipient as (the address that called this function), variable amount as _amt)
*/
	function withdrawReferral3InDAO(uint256 _amt) public {
		require((referralRecordMap[msg.sender].unclaimedRewards3InDAO >= _amt), "Insufficient referral rewards to withdraw");
		referralRecordMap[msg.sender].unclaimedRewards3InDAO  = (referralRecordMap[msg.sender].unclaimedRewards3InDAO - _amt);
		totalUnclaimedRewards3InDAO  = (totalUnclaimedRewards3InDAO - _amt);
		totalClaimedRewards3InDAO  = (totalClaimedRewards3InDAO + _amt);
		require((ERC20(address(0x17840DF7CAa07e298b16E8612157B90ED231C973)).balanceOf(address(this)) >= _amt), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((_amt > uint256(0))){
			ERC20(address(0x17840DF7CAa07e298b16E8612157B90ED231C973)).transfer(msg.sender, _amt);
		}
	}

/**
 * Function addReferral3
 * The function takes in 1 variable, (zero or a positive integer) _amt. It can only be called by other functions in this contract. It does the following :
 * creates an internal variable referringAddress with initial value referralRecordMap with element the address that called this function with element referringAddress
 * creates an internal variable referralsAllocatedInDAO with initial value 0
 * if not referralRecordMap with element the address that called this function with element hasDeposited then (updates referralRecordMap (Element the address that called this function) (Entity hasDeposited) as true)
 * if referringAddress is equals to Address 0 then (returns referralsAllocatedInDAO as output)
 * updates referralRecordMap (Element referringAddress) (Entity referralsAmt3AtLevel0) as (referralRecordMap with element referringAddress with element referralsAmt3AtLevel0) + (_amt)
 * updates referralRecordMap (Element referringAddress) (Entity referralsCount3AtLevel0) as (referralRecordMap with element referringAddress with element referralsCount3AtLevel0) + (1)
 * updates referralRecordMap (Element referringAddress) (Entity unclaimedRewards3InDAO) as (referralRecordMap with element referringAddress with element unclaimedRewards3InDAO) + (((2) * (_amt)) / (10))
 * updates referralsAllocatedInDAO as (referralsAllocatedInDAO) + (((2) * (_amt)) / (10))
 * updates referringAddress as referralRecordMap with element referringAddress with element referringAddress
 * updates totalUnclaimedRewards3InDAO as (totalUnclaimedRewards3InDAO) + (referralsAllocatedInDAO)
 * returns referralsAllocatedInDAO as output
*/
	function addReferral3(uint256 _amt) internal returns (uint256) {
		address referringAddress = referralRecordMap[msg.sender].referringAddress;
		uint256 referralsAllocatedInDAO = uint256(0);
		if (!(referralRecordMap[msg.sender].hasDeposited)){
			referralRecordMap[msg.sender].hasDeposited  = true;
		}
		if ((referringAddress == address(0))){
			return referralsAllocatedInDAO;
		}
		referralRecordMap[referringAddress].referralsAmt3AtLevel0  = (referralRecordMap[referringAddress].referralsAmt3AtLevel0 + _amt);
		referralRecordMap[referringAddress].referralsCount3AtLevel0  = (referralRecordMap[referringAddress].referralsCount3AtLevel0 + uint256(1));
		referralRecordMap[referringAddress].unclaimedRewards3InDAO  = (referralRecordMap[referringAddress].unclaimedRewards3InDAO + ((uint256(2) * _amt) / uint256(10)));
		referralsAllocatedInDAO  = (referralsAllocatedInDAO + ((uint256(2) * _amt) / uint256(10)));
		referringAddress  = referralRecordMap[referringAddress].referringAddress;
		totalUnclaimedRewards3InDAO  = (totalUnclaimedRewards3InDAO + referralsAllocatedInDAO);
		return referralsAllocatedInDAO;
	}

/**
 * Function addReferralAddress
 * The function takes in 1 variable, (an address) _referringAddress. It can only be called by functions outside of this contract. It does the following :
 * checks that referralRecordMap with element _referringAddress with element hasDeposited
 * checks that not _referringAddress is equals to (the address that called this function)
 * checks that (referralRecordMap with element the address that called this function with element referringAddress) is equals to Address 0
 * updates referralRecordMap (Element the address that called this function) (Entity referringAddress) as _referringAddress
 * emits event ReferralAddressAdded with inputs the address that called this function
*/
	function addReferralAddress(address _referringAddress) external {
		require(referralRecordMap[_referringAddress].hasDeposited, "Referring Address has not made a deposit");
		require(!((_referringAddress == msg.sender)), "Self-referrals are not allowed");
		require((referralRecordMap[msg.sender].referringAddress == address(0)), "User has previously indicated a referral address");
		referralRecordMap[msg.sender].referringAddress  = _referringAddress;
		emit ReferralAddressAdded(msg.sender);
	}

/**
 * Function mint1_StarTokenTaxWithdrawAmt
 * The function takes in 0 variables. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * checks that (ERC20(Address 0x8440178087C4fd348D43d0205F4574e0348a06F0)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to mint1_StarTokenAmtInBank
 * if mint1_StarTokenAmtInBank is strictly greater than 0 then (calls ERC20(Address 0x8440178087C4fd348D43d0205F4574e0348a06F0)'s at transfer function  with variable recipient as (the address that called this function), variable amount as mint1_StarTokenAmtInBank)
 * updates mint1_StarTokenAmtInBank as 0
*/
	function mint1_StarTokenTaxWithdrawAmt() public onlyOwner {
		require((ERC20(address(0x8440178087C4fd348D43d0205F4574e0348a06F0)).balanceOf(address(this)) >= mint1_StarTokenAmtInBank), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((mint1_StarTokenAmtInBank > uint256(0))){
			ERC20(address(0x8440178087C4fd348D43d0205F4574e0348a06F0)).transfer(msg.sender, mint1_StarTokenAmtInBank);
		}
		mint1_StarTokenAmtInBank  = uint256(0);
	}

/**
 * Function mint2_StarTokenV2TaxWithdrawAmt
 * The function takes in 0 variables. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * checks that (ERC20(Address 0xD289c01528921B5f6D5B111a50a99456D495bF78)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to mint2_StarTokenV2AmtInBank
 * if mint2_StarTokenV2AmtInBank is strictly greater than 0 then (calls ERC20(Address 0xD289c01528921B5f6D5B111a50a99456D495bF78)'s at transfer function  with variable recipient as (the address that called this function), variable amount as mint2_StarTokenV2AmtInBank)
 * updates mint2_StarTokenV2AmtInBank as 0
*/
	function mint2_StarTokenV2TaxWithdrawAmt() public onlyOwner {
		require((ERC20(address(0xD289c01528921B5f6D5B111a50a99456D495bF78)).balanceOf(address(this)) >= mint2_StarTokenV2AmtInBank), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((mint2_StarTokenV2AmtInBank > uint256(0))){
			ERC20(address(0xD289c01528921B5f6D5B111a50a99456D495bF78)).transfer(msg.sender, mint2_StarTokenV2AmtInBank);
		}
		mint2_StarTokenV2AmtInBank  = uint256(0);
	}

/**
 * Function mint3_DAOTaxWithdrawAmt
 * The function takes in 0 variables. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * checks that (ERC20(Address 0x17840DF7CAa07e298b16E8612157B90ED231C973)'s at balanceOf function  with variable recipient as (the address of this contract)) is greater than or equals to mint3_DAOAmtInBank
 * if mint3_DAOAmtInBank is strictly greater than 0 then (calls ERC20(Address 0x17840DF7CAa07e298b16E8612157B90ED231C973)'s at transfer function  with variable recipient as (the address that called this function), variable amount as mint3_DAOAmtInBank)
 * updates mint3_DAOAmtInBank as 0
*/
	function mint3_DAOTaxWithdrawAmt() public onlyOwner {
		require((ERC20(address(0x17840DF7CAa07e298b16E8612157B90ED231C973)).balanceOf(address(this)) >= mint3_DAOAmtInBank), "Insufficient amount of the token in this contract to transfer out. Please contact the contract owner to top up the token.");
		if ((mint3_DAOAmtInBank > uint256(0))){
			ERC20(address(0x17840DF7CAa07e298b16E8612157B90ED231C973)).transfer(msg.sender, mint3_DAOAmtInBank);
		}
		mint3_DAOAmtInBank  = uint256(0);
	}

/**
 * Function addToTransferTaxExclusionList0
 * The function takes in 1 variable, (an address) _addressToAdd. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * if check if _addressToAdd is inside transferTaxExclusionList0 then it does nothing else otherwise (adds _addressToAdd to transferTaxExclusionList0)
*/
	function addToTransferTaxExclusionList0(address _addressToAdd) public onlyOwner {
		if (isInside_address(_addressToAdd, transferTaxExclusionList0)){
		}else{
			transferTaxExclusionList0.push(_addressToAdd);
		}
	}

/**
 * Function removeFromTransferTaxExclusionList0
 * The function takes in 1 variable, (an address) _addressToAdd. It can be called by functions both inside and outside of this contract. It does the following :
 * checks that the function is called by the owner of the contract
 * if check if _addressToAdd is inside transferTaxExclusionList0 then (repeat length of transferTaxExclusionList0 times with loop variable i0 :  (if _addressToAdd is equals to (transferTaxExclusionList0 with element (Loop Variable i0) - (1)) then (if (length of transferTaxExclusionList0) is strictly greater than (Loop Variable i0) then (updates transferTaxExclusionList0 (Element (Loop Variable i0) - (1)) as transferTaxExclusionList0 with element (length of transferTaxExclusionList0) - (1)); and then removes last item from transferTaxExclusionList0)))
*/
	function removeFromTransferTaxExclusionList0(address _addressToAdd) public onlyOwner {
		if (isInside_address(_addressToAdd, transferTaxExclusionList0)){
			for (uint i0 = (transferTaxExclusionList0).length; i0 > 0; i0--){
				if ((_addressToAdd == transferTaxExclusionList0[(i0 - uint256(1))])){
					if (((transferTaxExclusionList0).length > i0)){
						transferTaxExclusionList0[(i0 - uint256(1))]  = transferTaxExclusionList0[((transferTaxExclusionList0).length - uint256(1))];
					}
					transferTaxExclusionList0.pop();
				}
			}
		}
	}

/**
 * Function burn
 * The function takes in 1 variable, (zero or a positive integer) _amount. It can be called by functions both inside and outside of this contract. It does the following :
 * calls super._burn with variable account as (the address that called this function), variable amount as _amount
 * returns true as output
*/
	function burn(uint256 _amount) public returns (bool) {
		super._burn(msg.sender, _amount);
		return true;
	}
}