/**
 *Submitted for verification at polygonscan.com on 2023-06-11
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// DISCLAIMER: This contract was generated by ChatGPT for educational purposes only. Use it at your own responsibility and risk.

contract Auction {
    address public highestBidder;
    uint256 public highestBid;
    uint256 public bidThreshold = 0.0001 ether;
    bool public biddingClosed;

    function placeBid() public payable {
        require(!biddingClosed, "Bidding is closed");
        require(msg.value > highestBid, "Bid amount must be higher than the current highest bid");

        // Refund the previous highest bidder if exists
        if (highestBidder != address(0)) {
            payable(highestBidder).transfer(highestBid);
        }

        highestBidder = msg.sender;
        highestBid = msg.value;

        // Check if bid threshold is reached to close the bidding and start a new round
        if (highestBid >= bidThreshold) {
            closeBidding();
            startNewRound();
        }
    }

    function closeBidding() private {
        biddingClosed = true;
    }

    function startNewRound() private {
        highestBidder = address(0);
        highestBid = 0;
        biddingClosed = false;
    }
}