/**
 *Submitted for verification at polygonscan.com on 2022-02-03
*/

// File: contracts/utils/random.sol


pragma solidity >=0.7.0 <0.9.0;

/*
#    Copyright (C) 2017  alianse777
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* "random" numbers generator (not cryptographicaly secure)
   rand(uint seed) - returns random number generated by seed
   randint() - returns random number with current time as seed
   randbytes(uint size) - returns byte array of random bytes
*/


contract Random {
    address owner;
    uint seed;
    modifier onlyOwner() {
        require (msg.sender == owner);
        _;
    }

    constructor(){ 
        //balances :D       
        owner = msg.sender;
    }

    function NewSeed(string memory _randomString)
        public                
        returns(uint256)
    {
    
        seed = (uint256(keccak256(abi.encodePacked(_randomString))))/(block.timestamp*100);
        return seed;
    }
   
    function rand(address _user)
        public
        view  
        returns(uint256)
    {
        uint balance = address(_user).balance;
        uint256 randNum = uint256(keccak256(abi.encodePacked(block.timestamp + block.difficulty + block.number + 
            ((uint256(keccak256(abi.encodePacked(_user,balance))))
             ))));
            return randNum;
    }   

    
    /**
     * @dev Generate random uint in range [a, b]
     * @return uint
     */
    function randrange(uint a, uint b,address _user) external view returns(uint) {
        return a + (rand(_user) % b);
    }
    function blockTime()public view returns(uint){
        return block.timestamp;
    }
    function blockNum()public view returns(uint){
        return block.number;
    }
    
}