// SPDX-License-Identifier: MIT
// compiler version must be greater than or equal to 0.8.10 and less than 0.9.0
pragma solidity ^0.8.10;

// generated by Github Copilot

contract TruffleVerify {
    string public greet = "This was verified using Truffle's plugin";
}