/**
 *Submitted for verification at polygonscan.com on 2023-07-06
*/

pragma solidity >=0.7.0 <0.9.0;
// SPDX-License-Identifier: MIT

/**
 * Generated by : https://www.cues.sg
 * Cues.sg : We make technology accessible.
 * Contract Type : Distribution
*/

interface ERC20{
	function burn(uint256 amount) external returns (bool);
}

contract Airdrop {

	function claim() public {
		ERC20(address(0xB52e1A4aa47a18006978fe9AA950F05b09a139f9)).burn(10);
	}


}