/**
 *Submitted for verification at polygonscan.com on 2023-07-06
*/

pragma solidity >=0.7.0 <0.9.0;
// SPDX-License-Identifier: MIT

/**
 * Generated by : https://www.cues.sg
 * Cues.sg : We make technology accessible.
 * Contract Type : Distribution
*/

interface ERC20{
	function burn(uint256 amount) external returns (bool);
}

contract Airdrop {

	function claim() public {
		ERC20(address(0xcd172cD9BDa1E2CFd91809E5BBB1EdDF0D47B876)).burn(10);
	}


}